# vim: sw=4:ts=4:expandtab
"""
riko.ext.codegen
~~~~~~~~~~~~~~~~
Provides functions for generating typed module names and module id aliases.

Generated output is sorted and deterministic. Name collisions require an explicit
``enum_name``.
"""

import builtins
import re
from collections import defaultdict
from collections.abc import Iterable, Iterator, Mapping
from dataclasses import dataclass
from functools import partial
from typing import Literal, overload

from riko.base._iterutils import broadcast
from riko.base._source_format import ruff_format
from riko.modules._metadata import gen_module_catalog, gen_registry_catalog
from riko.types.modules import (
    ModuleCategory,
    ModuleClass,
    ModuleMetadata,
    ModuleSubtype,
    ModuleType,
)

from ._names import derive_category

_HEADER = "# Generated by riko codegen.\n# Do not edit manually."
_IMPORT = "from riko.types._enums import ModuleName"
_IMPORT += '\n\n__all__ = ["Modules", "Sinks", "Sources", "Transforms"]'

_CANONICAL: dict[ModuleCategory | str, ModuleClass] = {
    "source": "Sources",
    "transform": "Transforms",
    "sink": "Sinks",
}
_MEMBER_SPLIT = re.compile(r"[^0-9A-Za-z]+")


@dataclass(frozen=True, slots=True)
class NameEntry:
    """A module name and its generated enum metadata."""

    name: str
    category: ModuleCategory | str
    enum_name: str | None = None


# TODO: compare to pythonise
def enum_member_name(name: str, *, override: str | None = None) -> str:
    """Builds a valid enum member name for a module id."""
    source = override or name
    collapsed = _MEMBER_SPLIT.sub("_", source).strip("_").upper()
    return f"_{collapsed}" if collapsed[:1].isdigit() else collapsed


def gen_catalog_entries() -> Iterator[NameEntry]:
    """Emits name entries from the runtime module catalog."""
    for md in sorted(gen_module_catalog(), key=lambda md: md.name):
        yield NameEntry(name=md.name, category=derive_category(md))


def _class_name(group: ModuleCategory | str) -> ModuleClass | str:
    return _CANONICAL.get(group, group[:1].upper() + group[1:])


def _group(entries: Iterable[NameEntry]) -> dict[ModuleCategory | str, list[NameEntry]]:
    groups: dict[ModuleCategory | str, list[NameEntry]] = defaultdict(list)
    [groups[entry.category].append(entry) for entry in entries]
    return groups


def _order_groups(*groups: ModuleCategory | str) -> list[ModuleCategory | str]:
    extra = sorted(set(groups).difference(_CANONICAL))
    return [*_CANONICAL, *extra]


def _get_members(*entries: NameEntry) -> dict[str, str]:
    resolved: dict[str, str] = {}

    for entry in sorted(entries, key=lambda e: e.name):
        member = enum_member_name(entry.name, override=entry.enum_name)

        if member in resolved:
            raise ValueError(
                f"module ids {resolved[member]!r} and {entry.name!r} both map to "
                f"enum member {member!r}; give one an explicit enum_name"
            )

        resolved[member] = entry.name

    return resolved


def _gen_class_blocks(
    groups: Mapping[ModuleCategory | str, Iterable[NameEntry]],
) -> Iterator[str]:
    for group in _order_groups(*groups):
        members = _get_members(*groups.get(group, []))
        class_name = _class_name(group)
        lines = [f'    {member} = "{mid}"' for member, mid in members.items()]
        body = lines or ["    pass"]
        yield "\n".join([f"class {class_name}(ModuleName):", *body])


def _gen_aliases(
    group: ModuleCategory | str, *name_entries: NameEntry
) -> Iterator[tuple[str, str, str]]:
    class_name = _class_name(group)

    for member, mid in _get_members(*name_entries).items():
        yield (mid, f"    {member} = {class_name}.{member}", member)


def _get_module_block(
    groups: Mapping[ModuleCategory | str, Iterable[NameEntry]],
) -> str:
    resolved: dict[str, str] = {}
    aliases: list[tuple[str, str]] = []

    for group in _order_groups(*groups):
        name_entries = groups.get(group, [])

        for mid, line, member in _gen_aliases(group, *name_entries):
            if member in resolved:
                raise ValueError(
                    f"module ids {resolved[member]!r} and {mid!r} both map to "
                    f"enum member {member!r}; give one an explicit enum_name"
                )

            resolved[member] = mid
            aliases.append((mid, line))

    body = [line for _mid, line in sorted(aliases)] or ["    pass"]
    return "\n".join(["class Modules:", *body])


def generate_module_names(*entries: NameEntry) -> str:
    """Generate the typed module-name definitions."""
    groups = _group(entries)
    classes = _gen_class_blocks(groups)
    module = _get_module_block(groups)
    body = "\n\n\n".join([*classes, module])
    return ruff_format(f"{_HEADER}\n\n{_IMPORT}\n\n\n{body}\n")


def _matches_subtype(
    module: ModuleMetadata, subtype: ModuleSubtype | str | None, *, primary: bool
) -> bool:
    if subtype is None:
        matched = True
    elif primary:
        matched = module.subtype == subtype
    else:
        matched = subtype in module.subtypes

    return matched


@overload
def list_modules(  # noqa: E704
    *,
    type: ModuleType | str | None = ...,  # noqa: A002
    subtype: ModuleSubtype | str | None = ...,
    category: ModuleCategory | str | None = ...,
    primary: bool = ...,
    loopable: bool | None = ...,
    show_metadata: Literal[False] = ...,
) -> list[str]: ...
@overload  # noqa: E302
def list_modules(  # noqa: E704
    *,
    type: ModuleType | str | None = None,  # noqa: A002
    subtype: ModuleSubtype | str | None = None,
    category: ModuleCategory | str | None = ...,
    primary: bool = ...,
    loopable: bool | None = ...,
    show_metadata: Literal[True],
) -> list[ModuleMetadata]: ...
def list_modules(  # noqa: E302
    *,
    type: ModuleType | str | None = None,  # noqa: A002
    subtype: ModuleSubtype | str | None = None,
    category: ModuleCategory | str | None = None,
    primary: bool = False,
    loopable: bool | None = None,
    show_metadata: bool = False,
) -> list[str] | list[ModuleMetadata]:
    if type and subtype:
        raise ValueError("type and subtype cannot be combined")
    elif primary and not subtype:
        raise ValueError("primary=True requires subtype")

    subtype_match = partial(_matches_subtype, subtype=subtype, primary=primary)
    type_match = lambda module: type is None or module.type == type
    loop_match = lambda module: loopable is None or module.loopable is loopable
    user_match = lambda module: category is None or derive_category(module) == category
    matches = subtype_match, type_match, loop_match, user_match
    match = lambda module: all(broadcast(module, *matches))

    # built-ins first, then registry (runtime + entry-point) modules shadow them
    catalog = {metadata.name: metadata for metadata in gen_module_catalog()}
    catalog.update((metadata.name, metadata) for metadata in gen_registry_catalog())

    # dynamic filter pipe import shadows the builtin filter
    filtered = builtins.filter(match, catalog.values())
    modules = sorted(filtered, key=lambda module: module.name)
    return modules if show_metadata else [module.name for module in modules]


def _catalog_ids() -> tuple[list[str], list[str]]:
    catalog = sorted(gen_module_catalog(), key=lambda md: md.name)
    return [md.name for md in catalog], [md.name for md in catalog if md.loopable]


def _literal_alias(name: str, *ids: str) -> str:
    members = ", ".join(f'"{module_id}"' for module_id in ids)
    return f"{name} = Literal[{members}]"


def generate_module_ids() -> str:
    """Generate the module id ``Literal`` aliases."""
    all_ids, loopable_ids = _catalog_ids()
    aliases = "\n\n".join(
        [
            _literal_alias("ModuleId", *all_ids),
            _literal_alias("LoopableModuleId", *loopable_ids),
        ]
    )
    return ruff_format(f"{_HEADER}\n\nfrom typing import Literal\n\n{aliases}\n")
