# vim: sw=4:ts=4:expandtab
"""
riko.ext.codegen
~~~~~~~~~~~~~~~~
Provides functions for generating typed module names and module id aliases.

Generated output is sorted and deterministic. Name collisions require an explicit
``enum_name``.
"""

import re
import subprocess
from collections import defaultdict
from collections.abc import Iterable, Iterator, Mapping
from dataclasses import dataclass

from riko.ext.names import derive_category
from riko.modules._metadata import gen_module_catalog
from riko.types.modules import ModuleCategory, ModuleClass

_HEADER = "# Generated by riko codegen.\n# Do not edit manually."
_IMPORT = "from riko.ext.names import ModuleName"
_IMPORT += '\n\n__all__ = ["Modules", "Sinks", "Sources", "Transforms"]'

_CANONICAL: dict[ModuleCategory | str, ModuleClass] = {
    "source": "Sources",
    "transform": "Transforms",
    "sink": "Sinks",
}
_MEMBER_SPLIT = re.compile(r"[^0-9A-Za-z]+")


def ruff_format(code: str) -> str:
    """Format generated code with Ruff when available."""
    try:
        result = subprocess.run(
            ["ruff", "format", "-"],  # noqa: S607
            input=code,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        formatted = code
    else:
        formatted = result.stdout or code

    return formatted


@dataclass(frozen=True, slots=True)
class NameEntry:
    """A module name and its generated enum metadata."""

    name: str
    category: ModuleCategory | str
    enum_name: str | None = None


# TODO: compare to pythonise
def enum_member_name(name: str, *, override: str | None = None) -> str:
    """Return a valid enum member name for a module id."""
    source = override or name
    collapsed = _MEMBER_SPLIT.sub("_", source).strip("_").upper()
    return f"_{collapsed}" if collapsed[:1].isdigit() else collapsed


def gen_catalog_entries() -> Iterator[NameEntry]:
    """Yield name entries from the runtime module catalog."""
    for md in sorted(gen_module_catalog(), key=lambda md: md.name):
        yield NameEntry(name=md.name, category=derive_category(md))


def _class_name(group: ModuleCategory | str) -> ModuleClass | str:
    return _CANONICAL.get(group, group[:1].upper() + group[1:])


def _group(entries: Iterable[NameEntry]) -> dict[ModuleCategory | str, list[NameEntry]]:
    groups: dict[ModuleCategory | str, list[NameEntry]] = defaultdict(list)
    [groups[entry.category].append(entry) for entry in entries]
    return groups


def _order_groups(*groups: ModuleCategory | str) -> list[ModuleCategory | str]:
    extra = sorted(set(groups).difference(_CANONICAL))
    return [*_CANONICAL, *extra]


def _get_members(*entries: NameEntry) -> dict[str, str]:
    resolved: dict[str, str] = {}

    for entry in sorted(entries, key=lambda e: e.name):
        member = enum_member_name(entry.name, override=entry.enum_name)

        if member in resolved:
            raise ValueError(
                f"module ids {resolved[member]!r} and {entry.name!r} both map to "
                f"enum member {member!r}; give one an explicit enum_name"
            )

        resolved[member] = entry.name

    return resolved


def _gen_class_blocks(
    groups: Mapping[ModuleCategory | str, Iterable[NameEntry]],
) -> Iterator[str]:
    for group in _order_groups(*groups):
        members = _get_members(*groups.get(group, []))
        class_name = _class_name(group)
        lines = [f'    {member} = "{mid}"' for member, mid in members.items()]
        body = lines or ["    pass"]
        yield "\n".join([f"class {class_name}(ModuleName):", *body])


def _gen_aliases(
    group: ModuleCategory | str, *name_entries: NameEntry
) -> Iterator[tuple[str, str, str]]:
    class_name = _class_name(group)

    for member, mid in _get_members(*name_entries).items():
        yield (mid, f"    {member} = {class_name}.{member}", member)


def _get_module_block(
    groups: Mapping[ModuleCategory | str, Iterable[NameEntry]],
) -> str:
    resolved: dict[str, str] = {}
    aliases: list[tuple[str, str]] = []

    for group in _order_groups(*groups):
        name_entries = groups.get(group, [])

        for mid, line, member in _gen_aliases(group, *name_entries):
            if member in resolved:
                raise ValueError(
                    f"module ids {resolved[member]!r} and {mid!r} both map to "
                    f"enum member {member!r}; give one an explicit enum_name"
                )

            resolved[member] = mid
            aliases.append((mid, line))

    body = [line for _mid, line in sorted(aliases)] or ["    pass"]
    return "\n".join(["class Modules:", *body])


def generate_module_names(*entries: NameEntry) -> str:
    """Generate the typed module-name definitions."""
    groups = _group(entries)
    classes = _gen_class_blocks(groups)
    module = _get_module_block(groups)
    body = "\n\n\n".join([*classes, module])
    return ruff_format(f"{_HEADER}\n\n{_IMPORT}\n\n\n{body}\n")


def _catalog_ids() -> tuple[list[str], list[str]]:
    catalog = sorted(gen_module_catalog(), key=lambda md: md.name)
    return [md.name for md in catalog], [md.name for md in catalog if md.loopable]


def _literal_alias(name: str, *ids: str) -> str:
    members = ", ".join(f'"{module_id}"' for module_id in ids)
    return f"{name} = Literal[{members}]"


def generate_module_ids() -> str:
    """Generate the module id ``Literal`` aliases."""
    all_ids, loopable_ids = _catalog_ids()
    aliases = "\n\n".join(
        [
            _literal_alias("ModuleId", *all_ids),
            _literal_alias("LoopableModuleId", *loopable_ids),
        ]
    )
    return ruff_format(f"{_HEADER}\n\nfrom typing import Literal\n\n{aliases}\n")
