#Pipe generated by pipe2python.py
#todo generate this import list:
from pipefetch import *
from pipefilter import *
from pipeoutput import *

def pipe_x():
    #demo

    sw_90 = pipe_fetch(None, conf={u'URL': {u'type': u'url', u'value': u'test/feed.xml'}})
    sw_102 = pipe_filter(sw_90, conf={u'COMBINE': {u'type': u'text', u'value': u'and'}, u'MODE': {u'type': u'text', u'value': u'permit'}, u'RULE': [{u'field': {u'type': u'text', u'value': u'title'}, u'value': {u'type': u'text', u'value': u'By'}, u'op': {u'type': u'text', u'value': u'contains'}}]})
    _OUTPUT = pipe_output(sw_102, conf=[])
    return _OUTPUT

if __name__ == "__main__":
    p = pipe_x()
    for i in p:
        print i

