# Pipe pipe_a3d1afa31f0a24cc51dcbe79f1590343 generated by pipe2py

from pipe2py.modules import pipeitembuilder, piperegex


def pipe_a3d1afa31f0a24cc51dcbe79f1590343(context=None, item=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [u'pipeitembuilder', u'piperegex']

    sw_163 = pipe_itembuilder(
        item, context, conf={
            'attrs':
                [
                    {
                        'value': {
                            'type': 'text',
                            'value': 'http://www.caltrain.com/Fares/farechart.html'},
                        'key': {'type': 'text', 'value': 'url'}}]})

    sw_134 = pipe_regex
    sw_134_conf={
        'RULE': [
            {
                'match': {'type': 'text', 'subkey': 'url'},
                'replace': {'type': 'text', 'value': 'fff'}}]}

    output = (sw_134(i, context=context, conf=sw_134_conf, **kwargs) for i in sw_163)
    return output



if __name__ == "__main__":
    pipeline = pipe_a3d1afa31f0a24cc51dcbe79f1590343()

    for i in pipeline:
        print i
