# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_82cdc3ce2af818cea73009f17cef4cd5 generated by pipe2py

from __future__ import (
    absolute_import, division, print_function, unicode_literals)

from os import path as p
from pprint import pprint
from twisted.internet.task import react
from pipe2py import Context
from pipe2py.lib.utils import combine_dicts as cdict
from pipe2py.lib.collections import SyncPipe
from pipe2py.twisted.collections import AsyncPipe

PARENT = p.dirname(p.dirname(p.dirname(__file__)))
make_regex = lambda f, m, r: {'field': f, 'match': m, 'replace': r}


def make_simplemath(other, op):
    return {'OTHER': {'subkey': other, 'type': 'number'}, 'OP': op}


def make_substring(_from, length):
    return {
        'from': {'type': 'integer', 'value': _from}
        , 'length': {'type': 'integer', 'value': length}
    }


def make_exchangerate(quote, offline=True):
    return {
        'quote': quote
        , 'default': DEF_CUR_CODE
        , 'offline': {'type': 'bool', 'value': offline}
    }


def make_tokenizer(to_str, dedupe=False, sort=False):
    return {
        'to-str': to_str
        , 'dedupe': {'type': 'bool', 'value': dedupe}
        , 'sort': {'type': 'bool', 'value': sort}
    }


def make_loop(
        _with, assign_to, embed_conf, pdictize=True, **kwargs
    ):

    return {
        'assign_part': kwargs.get('part', 'all'),
        'emit_part': kwargs.get('part', 'all'),
        'mode': kwargs.get('mode', 'assign'),
        'with': _with,
        'assign_to': assign_to,
        'embed': {'conf': embed_conf, 'pdictize': pdictize},
    }

DEF_CUR_CODE = 'USD'
mmatch = {'multilinematch': '4'}
smatch = {'singlelinematch': '2'}
pmatch = {'seriesmatch': False}
gmatch = {'globalmatch': '1'}
pmatch = {'seriesmatch': False}
cmatch = cdict(mmatch, smatch, pmatch)

rename_rule = [
    {'newval': '', 'field': 'y:title', 'op': 'rename'},
    {'newval': '', 'field': 'content', 'op': 'rename'},
    {'newval': 'k:posted', 'field': 'y:published', 'op': 'rename'},
    {'newval': 'k:job_type', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:content', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:work_location', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:client_location', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:tags', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:due', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:submissions', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:budget_raw', 'field': 'description', 'op': 'copy'},
    {'newval': 'k:marketplace', 'field': 'link', 'op': 'copy'},
    {'newval': 'k:author', 'field': 'title', 'op': 'copy'}]

match1_01 = '(.*)( - oDesk|\\| Elance Job)'
match1_02 = '^(http[s]?:\\/\\/)?\\/?([^\\/\\.]+\\.)*([^\\/\\.]+\\.[^:\\/\\s\\.]{2,3})(.*)'
match1_03 = '.*(Hourly budget:|Budget:<.*?> Hourly).*'
match1_04 = '.*(Fixed Price budget:|Budget:<.*?> Fixed Price).*'
match1_05 = '^(?!\\b(hourly|fixed)\\b).*'
match1_06 = '(.*)(<b>)?(Category|Budget):?(<.*?>)?(.*)'
match1_07 = '(.*)(<b>Description:<.*?>)(.*?)(<.*?>)(.*)'
match1_08 = '(.*)(<b>Proposals:<.*?>)(.*?)(<a href)(.*)'
match1_09 = '(.*)(<b>)(.*)'
match1_10 = '(.*)(\\bby\\b)(.*)'
match1_11 = '(.*)(<b>)(.*)'
match1_12 = '(.*)(<b>(Freelancer|Preferred Job) Location:<.*?>)(.*?)(<.*?>)(.*)'
match1_13 = '(.*)(<b>)(.*)'
match1_14 = '(.*)(<b>(Client Location:<.*?>|Country<.*?>:))(.*?)(<.*?>)(.*)'
match1_14b = '(.*)(<b>)(.*)'
match1_15 = '(.*)(<b>(Category:?<.*?>:?))(.*?)(<.*?>|<b>Skills<.*?>)(.*)'
match1_16 = '(.*)(<b>(Required skills|Desired Skills):<.*?>)(.*?)(<.*?>)(.*)'
match1_17 = '(.*)(Jobs:)(.*?)(\\))(.*)'
match1_18 = '&gt;|<br>'
match1_19 = '(\\w+)(?!.*,)'
match1_20 = '\\/|\\s*&amp;'
match1_21 = '[^\\w|\\-,]+'
match1_22 = '.*Time Left.*\\(Ends(.*)\\) <.*?>'
match1_23 = '(.*)(<b>)(.*)'
match1_24 = '(.*)((budget|Budget|Hourly budget.*Rate):?(<.*?>)?:?)\\s*(.*?)(<.*?>|, Jobs:)(.*)'
match1_24b = '^((?!(budget|Budget|Hourly budget.*Rate)).)*$'
match1_25 = 'Under|Upto|Less than|or less'
match1_26 = '^(?!.*-.*)(.*)'

regex_rule = [
    cdict(mmatch, smatch, make_regex('title', match1_01, '$1')),
    make_regex('k:marketplace', match1_02, '$3'),
    cdict(cmatch, make_regex('k:job_type', match1_03, 'hourly')),
    cdict(cmatch, make_regex('k:job_type', match1_04, 'fixed')),
    cdict(mmatch, smatch, make_regex('k:job_type', match1_05, 'unknown')),
    cdict(mmatch, smatch, make_regex('k:content', match1_06, '$1')),
    cdict(mmatch, smatch, make_regex('k:content', match1_07, '$3')),
    cdict(mmatch, smatch, make_regex('k:submissions', match1_08, '$3')),
    cdict(mmatch, smatch, make_regex('k:submissions', match1_09, 'unknown')),
    cdict(mmatch, smatch, make_regex('k:author', match1_10, '$3')),
    cdict(mmatch, smatch, make_regex('k:author', match1_11, 'unknown')),
    cdict(mmatch, smatch, make_regex('k:work_location', match1_12, '$4')),
    cdict(mmatch, smatch, make_regex('k:work_location', match1_13, 'unknown')),
    cdict(mmatch, smatch, make_regex('k:client_location', match1_14, '$4')),
    cdict(mmatch, smatch, make_regex('k:client_location', match1_14b, 'unknown')),
    cdict(cmatch, make_regex('k:tags', match1_15, '$4')),
    cdict(cmatch, make_regex('k:tags', match1_16, '$4')),
    cdict(cmatch, make_regex('k:tags', match1_17, '$3')),
    cdict(gmatch, make_regex('k:tags', match1_18, '')),
    # cdict(gmatch, make_regex('k:tags', match1_19, '$1,')),
    cdict(gmatch, make_regex('k:tags', match1_20, ',')),
    cdict(gmatch, make_regex('k:tags', match1_21, '-')),
    cdict(gmatch, make_regex('k:tags', '^-|-$', '')),
    cdict(gmatch, make_regex('k:tags', ',-|-,', ',')),
    cdict(gmatch, make_regex('k:tags', '^,|,$', '')),
    cdict(mmatch, smatch, make_regex('k:due', match1_22, '$1')),
    cdict(mmatch, smatch, make_regex('k:due', match1_23, 'unknown')),
    cdict(cmatch, make_regex('k:budget_raw', match1_24b, '0')),
    cdict(cmatch, make_regex('k:budget_raw', match1_24, '$5')),
    make_regex('k:budget_raw', 'k', '000'),
    make_regex('k:budget_raw', 'Under|Upto|Less than', '0 -'),
    make_regex('k:budget_raw', 'or less', '- 0'),
    make_regex('k:budget_raw', match1_26, '$1 - $1'),
]

my_item = {
    'content': '<p>Hello, I need to fix an application i am working on.\xa0\xa0Currently the rss has a cross origin problem, and i need to fix this.<br>\n<br>\nNext thing is i need to configure that the news will be read as an ion-list element, and a single article will be in a new page. with transition.<br>\n<br>\nThe application is in ionic + angular, so only experienced developers are welcome to this project.<br><br><b>Budget</b>: 10 EUR<br><b>Posted On</b>: December 27, 2014 13:32 UTC<br><b>ID</b>: 204946132<br><b>Category</b>: Web Development &gt; Web Programming<br><b>Skills</b>: Array<br><b>Country</b>: Israel<br><a href="https://www.odesk.com/jobs/Need-fix-Ionic-Rss-Reader-Application_%7E01d9a84fc5a0a79ddb?source=rss">click to apply</a></p>',
    'link': 'https://www.odesk.com/jobs/Need-fix-Ionic-Rss-Reader-Application_%7E01d9a84fc5a0a79ddb?source=rss',
    'pubDate': 'December 27, 2014',
    'summary': '<p>Hello, I need to fix an application i am working on.\xa0\xa0Currently the rss has a cross origin problem, and i need to fix this.<br>\n<br>\nNext thing is i need to configure that the news will be read as an ion-list element, and a single article will be in a new page. with transition.<br>\n<br>\nThe application is in ionic + angular, so only experienced developers are welcome to this project.<br><br><b>Budget</b>: 10 EUR<br><b>Posted On</b>: December 27, 2014 13:32 UTC<br><b>ID</b>: 204946132<br><b>Category</b>: Web Development &gt; Web Programming<br><b>Skills</b>: Array<br><b>Country</b>: Israel<br><a href="https://www.odesk.com/jobs/Need-fix-Ionic-Rss-Reader-Application_%7E01d9a84fc5a0a79ddb?source=rss">click to apply</a></p>',
    'title': 'Need to fix Ionic Rss Reader Application - oDesk',
    'updated': 'Sat, 27 Dec 2014 13:32:55 +0000',
    'y:id': None,
    'y:published': None,
    'y:title': 'Need to fix Ionic Rss Reader Application - oDesk'
}

itembuilder_attrs = [{'key': k, 'value': v} for k, v in my_item.items()]

sources = [
    {'url': 'http://feeds.feedburner.com/guru/all'}
    , {'url': 'http://feeds.feedburner.com/odesk/rss'}
    , {'url': 'http://feeds.feedburner.com/elance/all'}
    , {'url': 'http://feeds.feedburner.com/freelancer/all'}
    , {'url': 'http://feeds.feedburner.com/guru/it'}
    , {'url': 'http://feeds.feedburner.com/guru/design'}
    , {'url': 'http://feeds.feedburner.com/elance/it'}
    , {'url': 'http://feeds.feedburner.com/elance/design'}
]

abspath = p.abspath(p.join(PARENT, 'pipe2py', 'data', 'kazeeki3.json'))
url = "file://%s" % abspath
config = {
    'fetch': {'conf': {'URL': [s['url'] for s in sources]}, 'type': 'fetch'},
    'fetchdata': {'conf': {'URL': url, 'path': 'items'}, 'type': 'fetchdata'},
    'itembuilder': {'conf': {'attrs': itembuilder_attrs}, 'type': 'itembuilder'},
}

c = config['fetchdata']
skwargs = {'pdictize': False, 'conf': c['conf']}

def parse_source(source):
    fkwargs = [{'conf': {'RULE': rename_rule}}, {'conf': {'RULE': regex_rule}}]
    # pipe = source.dispatch(('rename', fkwargs[0]), ('regex', fkwargs[1]))
    pipe = source.rename(**fkwargs[0]).regex(**fkwargs[1])
    return pipe


def print_content(output):
    pipe = output.list
    pprint(pipe)
    print('count:', len(pipe))


def pipe_kazeeki(context=None):
    if context and context.describe_input:
        output = []

    elif context and context.describe_dependencies:
        output = []
    else:
        source = SyncPipe(c['type'], context=context, **skwargs)
        output = parse_source(source)
        # output = source.rename(conf={'RULE': rename_rule})

    return output


def asyncPipeKazeeki(reactor, context=None):
    if context and context.describe_input:
        output = []

    elif context and context.describe_dependencies:
        output = []
    else:
        source = AsyncPipe(c['type'], context=context, **skwargs)
        # output = parse_source(source)
        output = source.rename(conf={'RULE': rename_rule})

    output.addCallback(print_content)
    return output

if __name__ == "__main__":
    # output = pipe_kazeeki(Context())
    # print_content(output)
    react(asyncPipeKazeeki, [Context()])
