# Pipe test_pipeine generated by pipe2py

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch
from riko.modules.filter import pipe as _filter
from riko.types.modules import FetchRawConf, FilterRawConf, FilterRawRule


def pipe_testpipe1(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and (context.describe_input or context.describe_dependencies):
        return []

    sw_90 = fetch(
        context=context,
        conf=FetchRawConf({"url": {"type": "url", "value": get_path("feed.xml")}}),
    )

    sw_102 = _filter(
        sw_90,
        context=context,
        conf=FilterRawConf(
            {
                "combine": {"type": "text", "value": "and"},
                "permit": {"type": "bool", "value": True},
                "rule": [
                    FilterRawRule(
                        {
                            "field": {"type": "text", "value": "description"},
                            "value": {"type": "text", "value": "the"},
                            "op": {"type": "text", "value": "contains"},
                        }
                    )
                ],
            }
        ),
    )

    return sw_102


if __name__ == "__main__":
    context = Context()
    pipeline = pipe_testpipe1(context, None)

    for i in pipeline:
        print(i)
