# Pipe test_pipeine generated by pipe2py

from riko import Context
from riko.modules import pipefetch
from riko.modules import pipefilter


def pipe_testpipe1(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and (context.describe_input or context.describe_dependencies):
        return []

    sw_90 = pipefetch.pipe(
        context=context, conf={"URL": {"type": "url", "value": "file://data/feed.xml"}}
    )

    sw_102 = pipefilter.pipe(
        sw_90,
        context=context,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "MODE": {"type": "text", "value": "permit"},
            "RULE": [
                {
                    "field": {"type": "text", "value": "description"},
                    "value": {"type": "text", "value": "the"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    return sw_102


if __name__ == "__main__":
    context = Context()
    pipeline = pipe_testpipe1(context, None)

    for i in pipeline:
        print i
