# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_82cdc3ce2af818cea73009f17cef4cd5 generated by pipe2py

from os import path as p
from riko import get_path
from riko.compile import write_file
from riko.utils import combine_dicts as cdict


PARENT = p.dirname(p.dirname(p.dirname(__file__)))
make_regex = lambda f, m, r: {"field": f, "match": m, "replace": r}


pmatch = {"seriesmatch": False}

rename_rule = [
    {"newval": "", "field": "y:title", "copy": False},
    {"newval": "", "field": "content", "copy": False},
    {"newval": "k:posted", "field": "y:published", "copy": False},
    {"newval": "k:job_type", "field": "summary", "copy": True},
    {"newval": "k:content", "field": "summary", "copy": True},
    {"newval": "k:work_location", "field": "summary", "copy": True},
    {"newval": "k:client_location", "field": "summary", "copy": True},
    {"newval": "k:tags", "field": "summary", "copy": True},
    {"newval": "k:due", "field": "summary", "copy": True},
    {"newval": "k:submissions", "field": "summary", "copy": True},
    {"newval": "k:budget_raw", "field": "summary", "copy": True},
    {"newval": "k:marketplace", "field": "link", "copy": True},
    {"newval": "k:author", "field": "title", "copy": True},
]

match1_01 = "(.*)( - oDesk|\\| Elance Job)"
match1_02 = "^(http[s]?:\\/\\/)?\\/?([^\\/\\.]+\\.)*([^\\/\\.]+\\.[^:\\/\\s\\.]{2,3})(.*)"
match1_03 = ".*(Hourly budget:|Budget:<.*?> Hourly).*"
match1_04 = ".*(Fixed Price budget:|Budget:<.*?> Fixed Price).*"
match1_05 = "^(?!\\b(hourly|fixed)\\b).*"
match1_06 = "(.*)(<b>)?(Budget):?(<.*?>)?(.*)"
match1_07 = "(.*)(<b>Description:<.*?>)(.*?)(<.*?>)(.*)"
match1_08 = "(.*)(<b>Proposals:<.*?>)(.*?)(<a href)(.*)"
match1_09 = "(.*)(<b>)(.*)"
match1_10 = "(.*)(\\bby\\b)(.*)"
match1_11 = "(.*)(<b>)(.*)"
match1_12 = "(.*)(<b>(Freelancer|Preferred Job) Location:<.*?>)(.*?)(<.*?>)(.*)"
match1_13 = "(.*)(<b>)(.*)"
match1_14 = "(.*)(<b>(Client Location:<.*?>|Country<.*?>:))(.*?)(<.*?>)(.*)"
match1_14b = "(.*)(<b>)(.*)"
match1_15 = "(.*)(<b>(Category:?<.*?>:?))(.*?)(<.*?>|<b>Skills<.*?>)(.*)"
match1_16 = "(.*)(<b>(Required skills|Desired Skills):<.*?>)(.*?)(<.*?>)(.*)"
match1_17 = "(.*)(Jobs:)(.*?)(\\))(.*)"
match1_18 = "&gt;|<br>"
match1_19 = "(\\w+)(?!.*,)"
match1_20a = "\\/|\\s*&amp;"
match1_21a = "[^\\w|\\-,]+"
match1_22 = ".*Time Left.*\\(Ends(.*)\\) <.*?>"
match1_23 = "(.*)(<b>)(.*)"
match1_24b1 = "^((?!(budget|Budget|Hourly budget.*Rate)).)*$"
match1_24b2 = r"(.*)((budget|Budget|Hourly budget.*Rate):?(<.*?>)?:?)\s*(.*?)(<.*?>|, Jobs:)(.*)"
match1_25 = "Under|Upto|Less than"
match1_26 = "^(?!.*-.*)(.*)"

regex_rule = [
    make_regex("title", match1_01, "$1"),
    make_regex("k:marketplace", match1_02, "$3"),
    cdict(pmatch, make_regex("k:job_type", match1_03, "hourly")),
    cdict(pmatch, make_regex("k:job_type", match1_04, "fixed")),
    make_regex("k:job_type", match1_05, "unknown"),
    make_regex("k:content", match1_06, "$1"),
    make_regex("k:content", match1_07, "$3"),
    make_regex("k:submissions", match1_08, "$3"),
    make_regex("k:submissions", match1_09, "unknown"),
    make_regex("k:author", match1_10, "$3"),
    make_regex("k:author", match1_11, "unknown"),
    make_regex("k:work_location", match1_12, "$4"),
    make_regex("k:work_location", match1_13, "unknown"),
    make_regex("k:client_location", match1_14, "$4"),
    make_regex("k:client_location", match1_14b, "unknown"),
    cdict(pmatch, make_regex("k:tags", match1_15, "$4")),
    cdict(pmatch, make_regex("k:tags", match1_16, "$4")),
    cdict(pmatch, make_regex("k:tags", match1_17, "$3")),
    make_regex("k:tags", match1_18, ","),
    # make_regex('k:tags', match1_19, '$1,'),
    make_regex("k:tags", match1_20a, ","),
    make_regex("k:tags", match1_21a, "-"),
    make_regex("k:tags", "^-|-$", ""),
    make_regex("k:tags", ",-", ","),
    make_regex("k:tags", "-,", ","),
    make_regex("k:tags", "^,|,$", ""),
    make_regex("k:due", match1_22, "$1"),
    make_regex("k:due", match1_23, "unknown"),
    cdict(pmatch, make_regex("k:budget_raw", match1_24b1, "0")),
    cdict(pmatch, make_regex("k:budget_raw", match1_24b2, "$5")),
    make_regex("k:budget_raw", "k", "000"),
    make_regex("k:budget_raw", match1_25, "0 -"),
    make_regex("k:budget_raw", "or less", "- 0"),
    make_regex("k:budget_raw", match1_26, "$1 - $1"),
]

my_item = {
    "content": '<p>Hello, I need to fix an application i am working on. Currently the rss has a cross origin problem, and i need to fix this.<br>\n<br>\nNext thing is i need to configure that the news will be read as an ion-list element, and a single article will be in a new page. with transition.<br>\n<br>\nThe application is in ionic + angular, so only experienced developers are welcome to this project.<br><br><b>Budget</b>:Less than 10 EUR<br><b>Posted On</b>: December 27, 2014 13:32 UTC<br><b>ID</b>: 204946132<br><b>Category</b>: Web Development &gt; Web Programming<br><b>Skills</b>: Array<br><b>Country</b>: Israel<br><a href="https://www.odesk.com/jobs/Need-fix-Ionic-Rss-Reader-Application_%7E01d9a84fc5a0a79ddb?source=rss">click to apply</a></p>',
    "link": "https://www.odesk.com/jobs/Need-fix-Ionic-Rss-Reader-Application_%7E01d9a84fc5a0a79ddb?source=rss",
    "pubDate": "December 27, 2014",
    "summary": '<p>Hello, I need to fix an application i am working on. Currently the rss has a cross origin problem, and i need to fix this.<br>\n<br>\nNext thing is i need to configure that the news will be read as an ion-list element, and a single article will be in a new page. with transition.<br>\n<br>\nThe application is in ionic + angular, so only experienced developers are welcome to this project.<br><br><b>Budget</b>:Less than 10 EUR<br><b>Posted On</b>: December 27, 2014 13:32 UTC<br><b>ID</b>: 204946132<br><b>Category</b>: Web Development &gt; Web Programming<br><b>Skills</b>: Array<br><b>Country</b>: Israel<br><a href="https://www.odesk.com/jobs/Need-fix-Ionic-Rss-Reader-Application_%7E01d9a84fc5a0a79ddb?source=rss">click to apply</a></p>',
    "title": "Need to fix Ionic Rss Reader Application - oDesk",
    "updated": "Sat, 27 Dec 2014 13:32:55 +0000",
    "y:id": None,
    "y:published": None,
    "y:title": "Need to fix Ionic Rss Reader Application - oDesk",
}

itembuilder_attrs = [{"key": k, "value": v} for k, v in my_item.items()]
itembuilder_conf = {"attrs": itembuilder_attrs}
fetchdata_conf = {"URL": get_path("kazeeki2.json"), "path": "items"}
rename_conf = {"RULE": rename_rule}
regex_conf = {"RULE": regex_rule}


def write_content(content, pipe_name="kazeeki"):
    path = p.join(PARENT, "riko", "data", f"{pipe_name}.json")
    data = {"items": content}
    return write_file(data, path, True)
