# Pipe pipe_UuvYtuMe3hGDsmRgPm7D0g generated by pipe2py

from riko import Context
from riko.modules.strconcat import pipe as strconcat
from riko.modules.textinput import pipe as textinput
from riko.modules.strconcat import pipe as strconcat
from riko.modules.csv import pipe as csv
from riko.modules.filter import pipe as filter
from riko.modules.rename import pipe as rename
from riko.modules.loop import pipe as loop
from riko.modules.loop import pipe as loop


def pipe_UuvYtuMe3hGDsmRgPm7D0g(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [("", "name", "Name", "text", "Lancaster")]

    if context and context.describe_dependencies:
        return [
            "pipecsv",
            "pipefilter",
            "pipeloop",
            "pipeoutput",
            "piperename",
            "pipestrconcat",
            "pipetextinput",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_581(context=None, _INPUT=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return pipe_strconcat(
            context,
            _INPUT,
            conf={
                "part": [
                    {"type": "text", "subkey": "firstName"},
                    {"type": "text", "value": " "},
                    {"type": "text", "subkey": "Member"},
                ]
            },
        )

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_408(context=None, _INPUT=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return pipe_strconcat(
            context,
            _INPUT,
            conf={
                "part": [
                    {"type": "text", "value": "Total allowances claimed, inc travel: "},
                    {"type": "text", "subkey": "TotalAllowancesClaimedIncTravel"},
                    {
                        "type": "text",
                        "value": "<br>Total basic allowances claimed, ex travel: ",
                    },
                    {"type": "text", "subkey": "TotalBasicAllowancesExcTravel"},
                    {"type": "text", "value": "<br>Total Travel claimed: "},
                    {"type": "text", "subkey": "TotalTravelClaimed"},
                    {"type": "text", "value": "<br>MP Mileage: "},
                    {"type": "text", "subkey": "Mileage"},
                    {"type": "text", "value": "<br>MP Rail Travel: "},
                    {"type": "text", "subkey": "MPRail"},
                    {"type": "text", "value": "<br>MP Air Travel: "},
                    {"type": "text", "subkey": "MPAir"},
                    {
                        "type": "text",
                        "value": "<br>Cost of staying away from main home: ",
                    },
                    {"type": "text", "subkey": "CostofStayingAwayFromMainHome"},
                    {"type": "text", "value": "<br>London Supplement: "},
                    {"type": "text", "subkey": "LondonSupplement"},
                    {"type": "text", "value": "<br>Office Running Costs: "},
                    {"type": "text", "subkey": "OfficeRunningCosts"},
                    {"type": "text", "value": "<br>Staffing Costs: "},
                    {"type": "text", "subkey": "StaffingCosts"},
                ]
            },
        )

    sw_371 = textinput(
        context,
        conf={
            "debug": {"type": "text", "value": ""},
            "default": {"type": "text", "value": "Lancaster"},
            "prompt": {"type": "text", "value": "Name"},
            "name": {"type": "text", "value": "name"},
            "position": {"type": "number", "value": ""},
        },
    )

    sw_340 = csv(
        context,
        conf={
            "other_sep": {"type": "text", "value": ""},
            "URL": {
                "type": "url",
                "value": "file://data/spreadsheets.google.com_pub?key=p1rHUqg4g420UMaN1sPvaRg&output=csv&range=a1_AB646.csv",
            },
            "skip": {"type": "number", "value": "0"},
            "col_name": [
                {"type": "text", "value": "Member"},
                {"type": "text", "value": "firstName"},
                {"type": "text", "value": "TotalAllowancesClaimedIncTravel"},
                {"type": "text", "value": "TotalBasicAllowancesExcTravel"},
                {"type": "text", "value": "TotalTravelClaimed"},
                {"type": "text", "value": "CostofStayingAwayFromMainHome"},
                {"type": "text", "value": "LondonSupplement"},
                {"type": "text", "value": "OfficeRunningCosts"},
                {"type": "text", "value": "StaffingCosts"},
                {"type": "text", "value": "CentrallyPurchasedStationery"},
                {"type": "text", "value": "StationeryAssocdPostageCosts"},
                {"type": "text", "value": "CentralITProvision"},
                {"type": "text", "value": "StaffCoverAndOtherCosts"},
                {"type": "text", "value": "CommsAllowance"},
                {"type": "text", "value": "Mileage"},
                {"type": "text", "value": "MPRail"},
                {"type": "text", "value": "MPAir"},
                {"type": "text", "value": "MPMisc"},
                {"type": "text", "value": "MPOtherMileage"},
                {"type": "text", "value": "MPOtherRail"},
                {"type": "text", "value": "MPOtherAir"},
                {"type": "text", "value": "MPOtherEuropean"},
                {"type": "text", "value": "SpouseTotal"},
                {"type": "text", "value": "SpouseNumOfJourneys"},
                {"type": "text", "value": "FamilyTotal"},
                {"type": "text", "value": "FamilyNumOfJourneys"},
                {"type": "text", "value": "EmployeeTotal"},
                {"type": "text", "value": "EmployeeNumOfJourneys"},
            ],
            "col_row_start": {"type": "number", "value": "1"},
            "col_mode": {"type": "text", "value": "custom"},
            "separator": {"type": "text", "value": ","},
            "col_row_end": {"type": "number", "value": "1"},
        },
    )

    sw_375 = filter(
        context,
        sw_340,
        RULE_1_value=sw_371,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "permit": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "Member"},
                    "value": {"terminal": "RULE_1_value", "type": "text"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_385 = rename(
        context,
        sw_375,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "Member"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "title"},
                }
            ]
        },
    )

    sw_400 = loop(
        context,
        sw_385,
        embed=pipe_sw_408,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "description"},
            "emit": {"type": "bool", "value": False},
            "embed": {
                "type": "module",
                "value": {
                    "type": "strconcat",
                    "id": "sw-408",
                    "conf": {
                        "part": [
                            {
                                "type": "text",
                                "value": "Total allowances claimed, inc travel: ",
                            },
                            {
                                "type": "text",
                                "subkey": "TotalAllowancesClaimedIncTravel",
                            },
                            {
                                "type": "text",
                                "value": "<br>Total basic allowances claimed, ex travel: ",
                            },
                            {"type": "text", "subkey": "TotalBasicAllowancesExcTravel"},
                            {"type": "text", "value": "<br>Total Travel claimed: "},
                            {"type": "text", "subkey": "TotalTravelClaimed"},
                            {"type": "text", "value": "<br>MP Mileage: "},
                            {"type": "text", "subkey": "Mileage"},
                            {"type": "text", "value": "<br>MP Rail Travel: "},
                            {"type": "text", "subkey": "MPRail"},
                            {"type": "text", "value": "<br>MP Air Travel: "},
                            {"type": "text", "subkey": "MPAir"},
                            {
                                "type": "text",
                                "value": "<br>Cost of staying away from main home: ",
                            },
                            {"type": "text", "subkey": "CostofStayingAwayFromMainHome"},
                            {"type": "text", "value": "<br>London Supplement: "},
                            {"type": "text", "subkey": "LondonSupplement"},
                            {"type": "text", "value": "<br>Office Running Costs: "},
                            {"type": "text", "subkey": "OfficeRunningCosts"},
                            {"type": "text", "value": "<br>Staffing Costs: "},
                            {"type": "text", "subkey": "StaffingCosts"},
                        ]
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_573 = loop(
        context,
        sw_400,
        embed=pipe_sw_581,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "title"},
            "emit": {"type": "bool", "value": False},
            "embed": {
                "type": "module",
                "value": {
                    "type": "strconcat",
                    "id": "sw-581",
                    "conf": {
                        "part": [
                            {"type": "text", "subkey": "firstName"},
                            {"type": "text", "value": " "},
                            {"type": "text", "subkey": "Member"},
                        ]
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    return sw_573


if __name__ == "__main__":
    pipeline = pipe_UuvYtuMe3hGDsmRgPm7D0g(Context())

    for i in pipeline:
        print i
