# Pipe pipe_125e9fe8bb5f84526d21bebfec3ad116 generated by pipe2py

from riko import Context
from riko.modules.textinput import pipe as textinput
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.urlbuilder import pipe as urlbuilder
from riko.modules.loop import pipe as loop
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.loop import pipe as loop
from riko.modules.rename import pipe as rename


def pipe_125e9fe8bb5f84526d21bebfec3ad116(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [("", "textinput1", "Enter Text", "text", "defunkt")]

    if context and context.describe_dependencies:
        return [
            "pipefetchdata",
            "pipeitembuilder",
            "pipeloop",
            "pipeoutput",
            "piperename",
            "pipetextinput",
            "pipeurlbuilder",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_72(context=None, item=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return pipe_urlbuilder(context, _INPUT, conf=conf)

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_150(context=None, item=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return pipe_fetchdata(context, _INPUT, conf=conf)

    sw_479 = textinput(
        context,
        conf={
            "debug": {"type": "text", "value": "defunkt"},
            "default": {"type": "text", "value": "defunkt"},
            "prompt": {"type": "text", "value": "Enter Text"},
            "name": {"type": "text", "value": "textinput1"},
            "position": {"type": "number", "value": ""},
        },
    )

    sw_467 = itembuilder(
        context,
        conf={
            "attrs": [
                {
                    "value": {"terminal": "attrs_1_value", "type": "text"},
                    "key": {"type": "text", "value": "title"},
                }
            ]
        },
        attrs_1_value=sw_479,
    )

    sw_61 = loop(
        context,
        sw_467,
        embed=pipe_sw_72,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "api"},
            "emit": {"type": "bool", "value": False},
            "embed": {
                "type": "module",
                "value": {
                    "type": "urlbuilder",
                    "id": "sw-72",
                    "conf": {
                        "BASE": {
                            "type": "text",
                            "value": "https://api.github.com/search/users",
                        },
                        "PARAM": [
                            {
                                "value": {"type": "text", "subkey": "title"},
                                "key": {"type": "text", "value": "q"},
                            }
                        ],
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_142 = loop(
        context,
        sw_61,
        embed=pipe_sw_150,
        conf={
            "count": {"type": "text", "value": "first"},
            "assign": {"type": "text", "value": "info"},
            "emit": {"type": "bool", "value": False},
            "embed": {
                "type": "module",
                "value": {
                    "type": "fetchdata",
                    "id": "sw-150",
                    "conf": {
                        "URL": {"type": "url", "subkey": "api"},
                        "path": {"type": "text", "value": "items"},
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_351 = rename(
        context,
        sw_142,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "language.0.content"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "description"},
                }
            ]
        },
    )

    return sw_351


if __name__ == "__main__":
    pipeline = pipe_125e9fe8bb5f84526d21bebfec3ad116(Context())

    for i in pipeline:
        print i
