# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_e519dd393f943315f7e4128d19db2eac generated by riko

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.input import pipe as _input
from riko.modules.urlbuilder import pipe as urlbuilder
from riko.types.general import Conf
from riko.types.modules import FetchRawConf, InputRawConf, UrlBuilderRawConf


def pipe_e519dd393f943315f7e4128d19db2eac(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        _OUTPUT = [("", "q", "Search term:", "text", "enterprise mashup")]
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetch", "input", "urlbuilder"]
    else:
        sw_552 = _input(
            None,
            conf=InputRawConf(
                {
                    "debug": {"type": "text", "value": ""},
                    "default": {"type": "text", "value": "enterprise mashup"},
                    "name": {"type": "text", "value": "q"},
                    "position": {"type": "number", "value": ""},
                    "prompt": {"type": "text", "value": "Search term:"},
                }
            ),
            context=context,
        )
        sw_492 = urlbuilder(
            None,
            conf=UrlBuilderRawConf(
                {
                    "path": {"type": "text", "value": ""},
                    "base": {"type": "text", "value": "news.google.com/rss"},
                    "ext": {"type": "text", "value": "xml"},
                    "param": [
                        {
                            "key": {"type": "text", "value": "hl"},
                            "value": {"type": "text", "value": "en-US"},
                        },
                        {
                            "key": {"type": "text", "value": "gl"},
                            "value": {"type": "text", "value": "US"},
                        },
                        {
                            "key": {"type": "text", "value": "ceid"},
                            "value": {"type": "text", "value": "US:en"},
                        },
                        {
                            "key": {"type": "text", "value": "q"},
                            "value": {"terminal": "PARAM_5_value", "type": "text"},
                        },
                    ],
                }
            ),
            context=context,
            PARAM_5_value=sw_552,
        )
        sw_481 = fetch(
            None,
            conf=FetchRawConf(
                {
                    "url": {"terminal": "1_URL", "type": "url"},
                    "offline": {"type": "bool", "value": True},
                }
            ),
            context=context,
            _1_URL=sw_492,
        )
        _OUTPUT = sw_481

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_e519dd393f943315f7e4128d19db2eac():
        print(i)
