# Pipe pipe_402e244d09a4146cd80421c6628eb6d9 generated by pipe2py

from riko import Context
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.rename import pipe as rename
from riko.modules.regex import pipe as regex


def pipe_402e244d09a4146cd80421c6628eb6d9(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return ["pipefetchdata", "pipeoutput", "piperegex", "piperename"]

    sw_572 = fetchdata(
        context,
        conf={
            "URL": {
                "type": "url",
                "value": "file://data/www.bbc.co.uk_programmes_b006mvlc_episodes_player.xml",
            },
            "path": {"type": "text", "value": "episode"},
        },
    )

    sw_587 = rename(
        context,
        sw_572,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "programme.title"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "title"},
                },
                {
                    "field": {"type": "text", "value": "programme.pid"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "link"},
                },
                {
                    "field": {"type": "text", "value": "programme.short_synopsis"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "description"},
                },
            ]
        },
    )

    sw_598 = regex(
        context,
        sw_587,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "link"},
                    "match": {"type": "text", "value": "(.*)"},
                    "replace": {
                        "type": "text",
                        "value": "http://www.bbc.co.uk/programmes/$1",
                    },
                }
            ]
        },
    )

    return sw_598


if __name__ == "__main__":
    pipeline = pipe_402e244d09a4146cd80421c6628eb6d9(Context())

    for i in pipeline:
        print i
