# Pipe pipe_e65397e116d7754da0dd23425f1f0af1 generated by pipe2py

from riko import Context
from riko.modules.urlbuilder import pipe as urlbuilder
from riko.modules.fetch import pipe as fetch
from riko.modules.loop import pipe as loop
from riko.modules.rename import pipe as rename
from riko.modules.regex import pipe as regex


def pipe_e65397e116d7754da0dd23425f1f0af1(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "fetch",
            "loop",
            "regex",
            "rename",
            "urlbuilder",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_634(item=None, context=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return urlbuilder(
            item,
            context=context,
            conf={
                "PATH": {"type": "text", "value": ""},
                "BASE": {"type": "text", "value": ""},
                "PARAM": [
                    {
                        "value": {"type": "text", "value": "qr"},
                        "key": {"type": "text", "value": "cht"},
                    },
                    {
                        "value": {"type": "text", "value": "200x200"},
                        "key": {"type": "text", "value": "chs"},
                    },
                    {
                        "value": {"type": "text", "subkey": "link"},
                        "key": {"type": "text", "value": "chl"},
                    },
                ],
            },
            **kwargs
        )

    sw_565 = fetch(context, conf={"URL": {"type": "url", "value": ""}})

    sw_626 = loop(
        sw_565,
        context=context,
        embed=pipe_sw_634,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "media:content.url"},
            "emit": {"type": "bool", "value": False},
            "embed": {
                "type": "module",
                "value": {
                    "type": "urlbuilder",
                    "id": "sw-634",
                    "conf": {
                        "PATH": {"type": "text", "value": ""},
                        "BASE": {"type": "text", "value": ""},
                        "PARAM": [
                            {
                                "value": {"type": "text", "value": "qr"},
                                "key": {"type": "text", "value": "cht"},
                            },
                            {
                                "value": {"type": "text", "value": "200x200"},
                                "key": {"type": "text", "value": "chs"},
                            },
                            {
                                "value": {"type": "text", "subkey": "link"},
                                "key": {"type": "text", "value": "chl"},
                            },
                        ],
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_592 = rename(
        sw_626,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "media:content.url"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "description"},
                }
            ]
        },
    )

    sw_636 = regex(
        sw_592,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "description"},
                    "match": {"type": "text", "value": "(.*)"},
                    "replace": {
                        "type": "text",
                        "value": '<img src="$1" alt="QRcode" /><br/>${title}',
                    },
                }
            ]
        },
    )

    return sw_636


if __name__ == "__main__":
    pipeline = pipe_e65397e116d7754da0dd23425f1f0af1(Context())

    for i in pipeline:
        print(i)
