# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_dAI_R_FS3BG6fTKsAsqenA generated by riko

from riko import Context
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.loop import pipe as loop
from riko.modules.rename import pipe as rename
from riko.modules.strconcat import pipe as strconcat
from riko.types.general import Conf
from riko.types.modules import (
    FetchDataRawConf,
    LoopRawConf,
    RenameRawConf,
    StrconcatRawConf,
)


def pipe_dAI_R_FS3BG6fTKsAsqenA(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetchdata", "loop"]
    else:
        sw_286 = fetchdata(
            None,
            conf=FetchDataRawConf(
                {
                    "url": {
                        "type": "url",
                        "value": "file://riko/data/capnorth.oes.ca.gov_89509.xml",
                    },
                    "path": {"type": "text", "value": "info"},
                }
            ),
            context=context,
        )
        sw_138 = loop(
            sw_286,
            conf=LoopRawConf(
                {
                    "count": {"type": "text", "value": "all"},
                    "embed": {
                        "type": "module",
                        "value": {
                            "type": "strconcat",
                            "id": "sw-138e",
                            "emit": {"type": "bool", "value": False},
                            "assign": {"type": "text", "value": "title"},
                            "conf": StrconcatRawConf(
                                {
                                    "part": [
                                        {"type": "text", "subkey": "headline"},
                                        {"type": "text", "value": " ("},
                                        {"type": "text", "subkey": "severity"},
                                        {"type": "text", "value": ")"},
                                    ]
                                }
                            ),
                        },
                    },
                }
            ),
            context=context,
            embed=strconcat,
        )
        sw_180 = loop(
            sw_138,
            conf=LoopRawConf(
                {
                    "count": {"type": "text", "value": "all"},
                    "embed": {
                        "type": "module",
                        "value": {
                            "type": "rename",
                            "id": "sw-180e",
                            "emit": {"type": "bool", "value": True},
                            "assign": {"type": "text", "value": "loop:rename"},
                            "conf": RenameRawConf(
                                {
                                    "rule": [
                                        {
                                            "field": {
                                                "type": "text",
                                                "value": "expires",
                                            },
                                            "copy": {"type": "bool", "value": False},
                                            "newval": {
                                                "type": "text",
                                                "value": "pubDate",
                                            },
                                        }
                                    ]
                                }
                            ),
                        },
                    },
                }
            ),
            context=context,
            embed=rename,
        )
        _OUTPUT = sw_180

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_dAI_R_FS3BG6fTKsAsqenA():
        print(i)
