# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_58a53262da5a095fe7a0d6d905cc4db6 generated by riko

from riko import Context
from riko.collections import SyncCollection
from riko.modules.fetch import pipe as fetch
from riko.modules.reverse import pipe as reverse
from riko.modules.sort import pipe as sort
from riko.modules.truncate import pipe as truncate
from riko.modules.union import pipe as union
from riko.modules.urlbuilder import pipe as urlbuilder
from riko.types.general import Conf
from riko.types.modules import (
    FetchRawConf,
    SortRawConf,
    TruncateRawConf,
    UrlBuilderRawConf,
)


def pipe_58a53262da5a095fe7a0d6d905cc4db6(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetch", "reverse", "sort", "truncate", "union", "urlbuilder"]
    else:
        sw_606 = urlbuilder(
            None,
            conf=UrlBuilderRawConf(
                {
                    "base": {
                        "type": "text",
                        "value": "file://riko/data/www.greenhughes.com_rssfeed.xml",
                    },
                    "param": [
                        {
                            "key": {"type": "text", "value": ""},
                            "value": {"type": "text", "value": ""},
                        }
                    ],
                    "path": {"type": "text", "value": ""},
                }
            ),
            context=context,
        )
        sw_572 = fetch(
            None,
            conf=FetchRawConf({"url": {"terminal": "1_URL", "type": "url"}}),
            context=context,
            _1_URL=sw_606,
        )
        sw_550 = SyncCollection(
            [
                {"url": "file://riko/data/blog.ouseful.info_feed.xml"},
                {"url": "file://riko/data/feeds.feedburner.com_TheEdTechie.xml"},
            ],
            context=context,
        )
        sw_580 = union(sw_550, conf={}, context=context, OTHERS=[sw_572])
        sw_565 = sort(
            sw_580,
            conf=SortRawConf(
                {
                    "rule": [
                        {
                            "dir": {"type": "text", "value": "ASC"},
                            "field": {"type": "text", "value": "title"},
                        }
                    ]
                }
            ),
            context=context,
        )
        sw_596 = truncate(
            sw_565,
            conf=TruncateRawConf({"count": {"type": "number", "value": "3"}}),
            context=context,
        )
        sw_625 = reverse(sw_596, conf={}, context=context)
        _OUTPUT = sw_625

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_58a53262da5a095fe7a0d6d905cc4db6():
        print(i)
