# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_188eca77fd28c96c559f71f5729d91ec generated by riko

from riko import Context
from riko.modules.fetchpage import pipe as fetchpage
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.loop import pipe as loop
from riko.modules.truncate import pipe as truncate
from riko.types.general import Conf
from riko.types.modules import (
    FetchPageRawConf,
    ItemBuilderRawConf,
    LoopRawConf,
    TruncateRawConf,
)


def pipe_188eca77fd28c96c559f71f5729d91ec(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        result = []
    elif context and context.describe_dependencies:
        result = ["itembuilder", "loop", "truncate"]
    else:
        sw_163 = itembuilder(
            None,
            conf=ItemBuilderRawConf(
                {
                    "attrs": {
                        "key": {"type": "text", "value": "url"},
                        "value": {
                            "type": "text",
                            "value": "file://riko/data/www.caltrain.com_Fares_farechart.html",
                        },
                    }
                }
            ),
            context=context,
        )
        sw_111 = loop(
            sw_163,
            conf=LoopRawConf(
                {
                    "count": {"type": "text", "value": "all"},
                    "embed": {
                        "type": "module",
                        "value": {
                            "conf": FetchPageRawConf(
                                {
                                    "url": {"subkey": "url", "type": "url"},
                                    "start": {
                                        "type": "text",
                                        "value": "One Way</span>",
                                    },
                                    "end": {"type": "text", "value": "</tr>"},
                                    "token": {
                                        "type": "text",
                                        "value": '<td style="text-align: center;">',
                                    },
                                }
                            ),
                            "id": "sw-119",
                            "type": "fetchpage",
                            "emit": {"type": "bool", "value": True},
                            "assign": {"type": "text", "value": "loop:fetchpage"},
                        },
                    },
                }
            ),
            context=context,
            embed=fetchpage,
        )
        sw_287 = truncate(
            sw_111,
            conf=TruncateRawConf({"count": {"type": "number", "value": "100"}}),
            context=context,
        )
        _OUTPUT = sw_287
        result = _OUTPUT

    return result


if __name__ == "__main__":
    for i in pipe_188eca77fd28c96c559f71f5729d91ec():
        print(i)
