# Pipe pipe_UuvYtuMe3hGDsmRgPm7D0g generated by pipe2py

from riko import Context, get_path
from riko.modules.strconcat import pipe as strconcat
from riko.modules.input import pipe as textinput
from riko.modules.strconcat import pipe as strconcat
from riko.modules.csv import pipe as csv
from riko.modules.filter import pipe as _filter
from riko.modules.rename import pipe as rename
from riko.modules.loop import pipe as loop
from riko.modules.loop import pipe as loop


def pipe_UuvYtuMe3hGDsmRgPm7D0g(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [("", "name", "Name", "text", "Lancaster")]

    if context and context.describe_dependencies:
        return [
            "csv",
            "filter",
            "loop",
            "rename",
            "strconcat",
            "input",
        ]

    sw_371 = textinput(
        context=context,
        conf={
            "test": {"type": "bool", "value": "true"},
            "debug": {"type": "text", "value": ""},
            "default": {"type": "text", "value": "Lancaster"},
            "prompt": {"type": "text", "value": "Name"},
            "name": {"type": "text", "value": "name"},
        },
    )

    sw_340 = csv(
        context=context,
        conf={
            "other_sep": {"type": "text", "value": ""},
            "URL": {
                "type": "url",
                "value": get_path("spreadsheets.google.com_pub?key=p1rHUqg4g420UMaN1sPvaRg&output=csv&range=a1_AB646.csv"),
            },
            "skip_rows": {"type": "int", "value": "0"},
            "col_names": [
                {"type": "text", "value": "Member"},
                {"type": "text", "value": "firstName"},
                {"type": "text", "value": "TotalAllowancesClaimedIncTravel"},
                {"type": "text", "value": "TotalBasicAllowancesExcTravel"},
                {"type": "text", "value": "TotalTravelClaimed"},
                {"type": "text", "value": "CostofStayingAwayFromMainHome"},
                {"type": "text", "value": "LondonSupplement"},
                {"type": "text", "value": "OfficeRunningCosts"},
                {"type": "text", "value": "StaffingCosts"},
                {"type": "text", "value": "CentrallyPurchasedStationery"},
                {"type": "text", "value": "StationeryAssocdPostageCosts"},
                {"type": "text", "value": "CentralITProvision"},
                {"type": "text", "value": "StaffCoverAndOtherCosts"},
                {"type": "text", "value": "CommsAllowance"},
                {"type": "text", "value": "Mileage"},
                {"type": "text", "value": "MPRail"},
                {"type": "text", "value": "MPAir"},
                {"type": "text", "value": "MPMisc"},
                {"type": "text", "value": "MPOtherMileage"},
                {"type": "text", "value": "MPOtherRail"},
                {"type": "text", "value": "MPOtherAir"},
                {"type": "text", "value": "MPOtherEuropean"},
                {"type": "text", "value": "SpouseTotal"},
                {"type": "text", "value": "SpouseNumOfJourneys"},
                {"type": "text", "value": "FamilyTotal"},
                {"type": "text", "value": "FamilyNumOfJourneys"},
                {"type": "text", "value": "EmployeeTotal"},
                {"type": "text", "value": "EmployeeNumOfJourneys"},
            ],
            "delimiter": {"type": "text", "value": ","},
        },
    )

    sw_375 = _filter(
        sw_340,
        context=context,
        RULE_1_value=sw_371,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "PERMIT": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "Member"},
                    "value": {"terminal": "RULE_1_value", "type": "text"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_385 = loop(
        sw_375,
        context=context,
        embed=rename,
        conf={
            "count": {"type": "text", "value": "all"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "rename",
                    "emit": True,
                    "conf": {
                        "RULE": [
                            {
                                "field": {"type": "text", "value": "Member"},
                                "copy": {"type": "bool", "value": True},
                                "newval": {"type": "text", "value": "title"},
                            }
                        ]
                    },
                },
            },
        },
    )

    sw_400 = loop(
        sw_385,
        context=context,
        embed=strconcat,
        conf={
            "count": {"type": "text", "value": "all"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "strconcat",
                    "id": "sw-408",
                    "assign": "description",
                    "emit": False,
                    "conf": {
                        "part": [
                            {
                                "type": "text",
                                "value": "Total allowances claimed, inc travel: ",
                            },
                            {
                                "type": "text",
                                "subkey": "TotalAllowancesClaimedIncTravel",
                            },
                            {
                                "type": "text",
                                "value": "<br>Total basic allowances claimed, ex travel: ",
                            },
                            {"type": "text", "subkey": "TotalBasicAllowancesExcTravel"},
                            {"type": "text", "value": "<br>Total Travel claimed: "},
                            {"type": "text", "subkey": "TotalTravelClaimed"},
                            {"type": "text", "value": "<br>MP Mileage: "},
                            {"type": "text", "subkey": "Mileage"},
                            {"type": "text", "value": "<br>MP Rail Travel: "},
                            {"type": "text", "subkey": "MPRail"},
                            {"type": "text", "value": "<br>MP Air Travel: "},
                            {"type": "text", "subkey": "MPAir"},
                            {
                                "type": "text",
                                "value": "<br>Cost of staying away from main home: ",
                            },
                            {"type": "text", "subkey": "CostofStayingAwayFromMainHome"},
                            {"type": "text", "value": "<br>London Supplement: "},
                            {"type": "text", "subkey": "LondonSupplement"},
                            {"type": "text", "value": "<br>Office Running Costs: "},
                            {"type": "text", "subkey": "OfficeRunningCosts"},
                            {"type": "text", "value": "<br>Staffing Costs: "},
                            {"type": "text", "subkey": "StaffingCosts"},
                        ]
                    },
                },
            },
        },
    )

    sw_573 = loop(
        sw_400,
        context=context,
        embed=strconcat,
        conf={
            "count": {"type": "text", "value": "all"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "strconcat",
                    "id": "sw-581",
                    "assign": "title",
                    "emit": False,
                    "conf": {
                        "part": [
                            {"type": "text", "subkey": "firstName"},
                            {"type": "text", "value": " "},
                            {"type": "text", "subkey": "Member"},
                        ]
                    },
                },
            },
        },
    )

    return sw_573


if __name__ == "__main__":
    pipeline = pipe_UuvYtuMe3hGDsmRgPm7D0g(Context())

    for i in pipeline:
        print(i)
