# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_zKJifuNS3BGLRQK_GsevXg generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.count import pipe as count
from riko.modules.fetch import pipe as fetch
from riko.modules.simplemath import pipe as simplemath
from riko.modules.split import pipe as split
from riko.modules.truncate import pipe as truncate
from riko.types.modules import (
    CountRawConf,
    FetchRawConf,
    SimpleMathRawConf,
    SplitRawConf,
    TruncateRawConf
)


def pipe_zKJifuNS3BGLRQK_GsevXg(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ['count', 'fetch', 'simplemath', 'split', 'truncate']
    else:
        sw_224 = fetch(item, conf=FetchRawConf({'url': {'type': 'url', 'value': 'file://riko/data/TheEdTechie.xml'}}), context=context)
        splits = split(sw_224, conf=SplitRawConf(), context=context)
        sw_250_0 = list(next(splits))
        sw_250_1 = list(next(splits))
        sw_242 = count(iter(sw_250_1), conf=CountRawConf(), assign='content', context=context)
        splits = split(sw_242, conf=SplitRawConf(), context=context)
        sw_243_0 = list(next(splits))
        sw_243_1 = list(next(splits))
        sw_94 = simplemath(iter(sw_243_0), conf=SimpleMathRawConf({'op': {'type': 'text', 'value': 'modulo'}, 'other': {'type': 'float', 'value': '6'}}), emit=True, context=context)
        sw_169 = simplemath(iter(sw_243_0), conf=SimpleMathRawConf({'op': {'type': 'text', 'value': 'subtract'}, 'other': {'terminal': 'OTHER', 'type': 'float'}}), emit=True, context=context, OTHER=sw_94)
        sw_232 = truncate(iter(sw_250_0), conf=TruncateRawConf({'count': {'terminal': 'count', 'type': 'float'}}), context=context, count=sw_169)
        _OUTPUT = sw_232

    return _OUTPUT


mark_subpipe(pipe_zKJifuNS3BGLRQK_GsevXg, subtype="source")


if __name__ == "__main__":
    for i in pipe_zKJifuNS3BGLRQK_GsevXg():
        print(i)