# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_402e244d09a4146cd80421c6628eb6d9 generated by riko

from riko import Context
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.regex import pipe as regex
from riko.modules.rename import pipe as rename
from riko.types.modules import FetchDataRawConf, RegexRawConf, RenameRawConf


def pipe_402e244d09a4146cd80421c6628eb6d9(
    item=None, context: Context | None = None, **_
):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetchdata", "regex", "rename"]
    else:
        sw_572 = fetchdata(
            item,
            conf=FetchDataRawConf(
                {
                    "url": {
                        "type": "url",
                        "value": "file://riko/data/www.bbc.co.uk_programmes_b006mvlc_episodes_player.xml",
                    },
                    "path": {"type": "text", "value": "episode"},
                }
            ),
            context=context,
        )
        sw_587 = rename(
            sw_572,
            conf=RenameRawConf(
                {
                    "rule": [
                        {
                            "field": {"type": "text", "value": "programme.title"},
                            "copy": {"type": "bool", "value": True},
                            "newval": {"type": "text", "value": "title"},
                        },
                        {
                            "field": {"type": "text", "value": "programme.pid"},
                            "copy": {"type": "bool", "value": True},
                            "newval": {"type": "text", "value": "link"},
                        },
                        {
                            "field": {
                                "type": "text",
                                "value": "programme.short_synopsis",
                            },
                            "copy": {"type": "bool", "value": True},
                            "newval": {"type": "text", "value": "description"},
                        },
                    ]
                }
            ),
            emit=True,
            assign="loop:rename",
            count="all",
            context=context,
        )
        sw_598 = regex(
            sw_587,
            conf=RegexRawConf(
                {
                    "rule": [
                        {
                            "field": {"type": "text", "value": "link"},
                            "match": {"type": "text", "value": "(.*)"},
                            "replace": {
                                "type": "text",
                                "value": "http://www.bbc.co.uk/programmes/$1",
                            },
                        }
                    ]
                }
            ),
            emit=True,
            assign="loop:regex",
            count="all",
            context=context,
        )
        _OUTPUT = sw_598

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_402e244d09a4146cd80421c6628eb6d9():
        print(i)
