# Pipe pipe_bd0834cfe6cdacb0bea5569505d330b8 generated by pipe2py

from riko import Context
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.input import pipe as textinput
from riko.modules.urlbuilder import pipe as urlbuilder


def pipe_bd0834cfe6cdacb0bea5569505d330b8(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [("", "gid", "MP Guardian ID", "text", "1276")]

    if context and context.describe_dependencies:
        return ["fetchdata", "input", "urlbuilder"]

    sw_606 = textinput(
        context=context,
        conf={
            "test": {"type": "bool", "value": "true"},
            "debug": {"type": "text", "value": ""},
            "default": {"type": "text", "value": "1276"},
            "prompt": {"type": "text", "value": "MP Guardian ID"},
            "name": {"type": "text", "value": "gid"},
        },
    )

    sw_579 = urlbuilder(
        context=context,
        _1_PATH=sw_606,
        conf={
            "PATH": [
                {"terminal": "1_PATH", "type": "text"},
                {"type": "text", "value": "json"},
            ],
            "BASE": {"type": "text", "value": ""},
            "PARAM": [
                {
                    "value": {"type": "text", "value": ""},
                    "key": {"type": "text", "value": ""},
                }
            ],
        },
    )

    sw_610 = fetchdata(
        context=context,
        URL=sw_579,
        conf={
            "URL": {"terminal": "URL", "type": "url"},
            "path": {"type": "text", "value": "person"},
        },
    )

    return sw_610


if __name__ == "__main__":
    pipeline = pipe_bd0834cfe6cdacb0bea5569505d330b8(Context())

    for i in pipeline:
        print(i)
