# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_8NMkiTW32xGvMbDKruymrA generated by riko

from riko import Context
from riko.collections import SyncCollection
from riko.modules.filter import pipe as _filter
from riko.modules.sort import pipe as sort
from riko.types.general import Conf
from riko.types.modules import FilterRawConf, SortRawConf


def pipe_8NMkiTW32xGvMbDKruymrA(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        result = []
    elif context and context.describe_dependencies:
        result = ["fetch", "filter", "sort"]
    else:
        sw_35 = SyncCollection(
            [
                {"url": "file://riko/data/www.fourtitude.com_news_publish_rss.xml"},
                {"url": "file://riko/data/feeds.gawker.com_jalopnik_full.xml"},
                {"url": "file://riko/data/www.autoblog.com_rss.xml"},
            ],
            context=context,
        )
        sw_54 = _filter(
            sw_35,
            conf=FilterRawConf(
                {
                    "combine": {"type": "text", "value": "or"},
                    "permit": {"type": "bool", "value": True},
                    "rule": [
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Porsche"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Mercedes"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "BMW"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Audi"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "VW"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Lamborghini"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Ferrari"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Pagani"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Aston"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "Lotus"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "TVR"},
                        },
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "AMG"},
                        },
                    ],
                }
            ),
            context=context,
        )
        sw_105 = sort(
            sw_54,
            conf=SortRawConf(
                {
                    "rule": [
                        {
                            "dir": {"type": "text", "value": "DESC"},
                            "field": {"type": "text", "value": "pubDate"},
                        }
                    ]
                }
            ),
            context=context,
        )
        _OUTPUT = sw_105
        result = _OUTPUT

    return result


if __name__ == "__main__":
    for i in pipe_8NMkiTW32xGvMbDKruymrA():
        print(i)
