# Pipe pipe_HrX5bjkv3BGEp9eSy6ky6g generated by pipe2py

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch
from riko.modules.feedautodiscovery import pipe as feedautodiscovery
from riko.modules.loop import pipe as loop
from riko.modules.sort import pipe as sort
from riko.modules.truncate import pipe as truncate


def pipe_HrX5bjkv3BGEp9eSy6ky6g(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "feedautodiscovery",
            "fetch",
            "loop",
            "sort",
            "truncate",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_165(item=None, context=None, conf=None, **kwargs):

        # todo: insert submodule description here
        return fetch(
            item, context=context, conf={"URL": {"type": "url", "subkey": "link"}}, **kwargs
        )

    sw_149 = feedautodiscovery(
        context=context,
        conf={"URL": {"type": "url", "value": get_path("edition.cnn.html")}},
    )

    sw_157 = loop(
        sw_149,
        context=context,
        embed=pipe_sw_165,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "loop:fetch"},
            "emit": {"type": "bool", "value": True},
            "embed": {
                "type": "module",
                "value": {
                    "type": "fetch",
                    "id": "sw-165",
                    "conf": {"URL": {"type": "url", "subkey": "link"}},
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_174 = sort(
        sw_157,
        context=context,
        conf={
            "KEY": [
                {
                    "field": {"type": "text", "value": "pubDate"},
                    "dir": {"type": "text", "value": "ASC"},
                }
            ]
        },
    )

    sw_191 = truncate(
        sw_174, context=context, conf={"count": {"type": "int", "value": "25"}}
    )

    return sw_149


if __name__ == "__main__":
    pipeline = pipe_HrX5bjkv3BGEp9eSy6ky6g(Context())

    for i in pipeline:
        print(i)
