# Pipe pipe_926a27580e74684fc63559b92bddaa30 generated by pipe2py

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.uniq import pipe as uniq
from riko.modules.filter import pipe as _filter
from riko.modules.sort import pipe as sort


def pipe_926a27580e74684fc63559b92bddaa30(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    sw_68 = fetch(
        context=context,
        conf={
            "URL": [
                {
                    "type": "url",
                    "value": "http://www.guru.com/rss/jobs/c/web-software-it/",
                },
                {
                    "type": "url",
                    "value": "https://www.elance.com/r/rss/jobs/cat-it-programming/fxd-true/o-1/bgt-gt500-ns1/sct-database-development-10217-data-analysis-14174-database-administration-14177-business-intelligence-14173-data-engineering-14175-system-administration-10219-other-data-science-14178-technical-support-10218-other-it-programming-12350-software-application-10216-website-design-10225-web-programming-10224/tls-1/s-timelistedSort",
                },
            ]
        },
    )

    sw_90 = uniq(sw_68, context=context, conf={"field": {"type": "text", "value": "link"}})

    sw_87 = _filter(
        sw_90,
        context=context,
        conf={
            "COMBINE": {"type": "text", "value": "or"},
            "PERMIT": {"type": "bool", "value": False},
            "RULE": [
                {
                    "field": {"type": "text", "value": "title"},
                    "value": {"type": "text", "value": "php"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_101 = sort(
        sw_87,
        context=context,
        conf={
            "KEY": [
                {
                    "field": {"type": "text", "value": "pubDate"},
                    "dir": {"type": "text", "value": "DESC"},
                }
            ]
        },
    )

    return sw_101


if __name__ == "__main__":
    context = Context()
    pipeline = pipe_926a27580e74684fc63559b92bddaa30(context, None)

    for i in pipeline:
        print(i)
