# Pipe pipe_eb3e27f8f1841835fdfd279cd96ff9d8 generated by pipe2py

from riko import Context
from riko.modules.urlinput import pipe as urlinput
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.textinput import pipe as textinput
from riko.modules.filter import pipe as filter
from riko.modules.rename import pipe as rename
from riko.modules.regex import pipe as regex


def pipe_eb3e27f8f1841835fdfd279cd96ff9d8(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [
            ("", "q", "Caption search term", "text", "maverick"),
            (
                "",
                "url",
                "Caption URL",
                "url",
                "file://data/rsc-ne-scotland.org.uk_mashe_ititle_xml_jisc10bean.xml",
            ),
        ]

    if context and context.describe_dependencies:
        return [
            "pipefetchdata",
            "pipefilter",
            "pipeoutput",
            "piperegex",
            "piperename",
            "pipetextinput",
            "pipeurlinput",
        ]

    sw_521 = urlinput(
        context,
        conf={
            "debug": {"type": "url", "value": ""},
            "default": {
                "type": "url",
                "value": "file://data/rsc-ne-scotland.org.uk_mashe_ititle_xml_jisc10bean.xml",
            },
            "prompt": {"type": "text", "value": "Caption URL"},
            "name": {"type": "text", "value": "url"},
            "position": {"type": "number", "value": ""},
        },
    )

    sw_572 = fetchdata(
        context,
        URL=sw_521,
        conf={
            "URL": {"terminal": "URL", "type": "url"},
            "path": {"type": "text", "value": "body.div.p"},
        },
    )

    sw_621 = textinput(
        context,
        conf={
            "debug": {"type": "text", "value": ""},
            "default": {"type": "text", "value": "maverick"},
            "prompt": {"type": "text", "value": "Caption search term"},
            "name": {"type": "text", "value": "q"},
            "position": {"type": "number", "value": ""},
        },
    )

    sw_584 = filter(
        context,
        sw_572,
        RULE_1_value=sw_621,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "MODE": {"type": "text", "value": "permit"},
            "RULE": [
                {
                    "field": {"type": "text", "value": "content"},
                    "value": {"terminal": "RULE_1_value", "type": "text"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_595 = rename(
        context,
        sw_584,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "begin"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "ctime"},
                },
                {
                    "field": {"type": "text", "value": "content"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "title"},
                },
            ]
        },
    )

    sw_606 = regex(
        context,
        sw_595,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "ctime"},
                    "match": {"type": "text", "value": "(.*)"},
                    "replace": {"type": "text", "value": "&time=$1"},
                }
            ]
        },
    )

    return sw_606


if __name__ == "__main__":
    pipeline = pipe_eb3e27f8f1841835fdfd279cd96ff9d8(Context())

    for i in pipeline:
        print i
