# Pipe pipe_1166de33b0ea6936d96808717355beaa generated by pipe2py

from riko import Context
from riko.modules.rssitembuilder import pipe as rssitembuilder
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.union import pipe as union
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.loop import pipe as loop
from riko.modules.loop import pipe as loop
from riko.modules.union import pipe as union


def pipe_1166de33b0ea6936d96808717355beaa(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "itembuilder",
            "loop",
            "rssitembuilder",
            "union",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_710(item=None, context=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return itembuilder(
            item,
            context=context,
            conf={
                "attrs": [
                    {
                        "value": {"type": "text", "subkey": "newtitle"},
                        "key": {"type": "text", "value": "title"},
                    },
                    {
                        "value": {"type": "text", "value": "DESCRIPTION"},
                        "key": {"type": "text", "value": "description.content"},
                    },
                ]
            },
            **kwargs
        )

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_696(item=None, context=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return itembuilder(
            item,
            context=context,
            conf={
                "attrs": [
                    {
                        "value": {"type": "text", "value": "NEWTITLE"},
                        "key": {"type": "text", "value": "newtitle"},
                    },
                    {
                        "value": {"type": "text", "subkey": "title"},
                        "key": {"type": "text", "value": "title"},
                    },
                ]
            },
            **kwargs
        )

    sw_674 = rssitembuilder(
        context=context,
        conf={
            "mediaContentHeight": {"type": "text", "value": ""},
            "mediaThumbURL": {"type": "text", "value": "http://example.com/a.jpg"},
            "mediaContentType": {"type": "text", "value": ""},
            "description": {"type": "text", "value": "b"},
            "pubdate": {"type": "text", "value": ""},
            "author": {"type": "text", "value": ""},
            "title": {"type": "text", "value": "a"},
            "mediaThumbHeight": {"type": "text", "value": ""},
            "link": {"type": "text", "value": "http://example.com/test.php?this=that"},
            "mediaContentWidth": {"type": "text", "value": ""},
            "mediaContentURL": {"type": "text", "value": ""},
            "guid": {"type": "text", "value": ""},
            "mediaThumbWidth": {"type": "text", "value": ""},
        },
    )

    sw_554 = itembuilder(
        context=context,
        conf={
            "attrs": [
                {
                    "value": {"type": "text", "value": "TITLE1"},
                    "key": {"type": "text", "value": "title"},
                }
            ]
        },
    )

    sw_569 = itembuilder(
        context=context,
        conf={
            "attrs": [
                {
                    "value": {"type": "text", "value": "TITLE2"},
                    "key": {"type": "text", "value": "title"},
                },
                {
                    "value": {"type": "text", "value": "DESC"},
                    "key": {"type": "text", "value": "description"},
                },
                {
                    "value": {"type": "text", "value": "GONE"},
                    "key": {"type": "text", "value": "lostattribute"},
                },
            ]
        },
    )

    sw_637 = union(sw_554, context=context, _OTHER2=sw_569, conf={})

    sw_656 = loop(
        sw_637,
        context=context,
        embed=pipe_sw_696,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "loop:itembuilder"},
            "emit": {"type": "bool", "value": True},
            "embed": {
                "type": "module",
                "value": {
                    "type": "itembuilder",
                    "id": "sw-696",
                    "conf": {
                        "attrs": [
                            {
                                "value": {"type": "text", "value": "NEWTITLE"},
                                "key": {"type": "text", "value": "newtitle"},
                            },
                            {
                                "value": {"type": "text", "subkey": "title"},
                                "key": {"type": "text", "value": "title"},
                            },
                        ]
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_688 = loop(
        sw_656,
        context=context,
        embed=pipe_sw_710,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "loop:itembuilder"},
            "emit": {"type": "bool", "value": False},
            "embed": {
                "type": "module",
                "value": {
                    "type": "itembuilder",
                    "id": "sw-710",
                    "conf": {
                        "attrs": [
                            {
                                "value": {"type": "text", "subkey": "newtitle"},
                                "key": {"type": "text", "value": "title"},
                            },
                            {
                                "value": {"type": "text", "value": "DESCRIPTION"},
                                "key": {"type": "text", "value": "description.content"},
                            },
                        ]
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_730 = union(sw_674, context=context, _OTHER2=sw_688, conf={})

    return sw_730


if __name__ == "__main__":
    pipeline = pipe_1166de33b0ea6936d96808717355beaa(Context())

    for i in pipeline:
        print(i)
