# Pipe pipe_125e9fe8bb5f84526d21bebfec3ad116 generated by pipe2py

from riko import Context
from riko.modules.input import pipe as textinput
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.urlbuilder import pipe as urlbuilder
from riko.modules.loop import pipe as loop
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.loopy import pipe as loopy
from riko.modules.rename import pipe as rename


def pipe_125e9fe8bb5f84526d21bebfec3ad116(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [("", "textinput1", "Enter Text", "text", "defunkt")]

    if context and context.describe_dependencies:
        return [
            "fetchdata",
            "itembuilder",
            "loop",
            "loopy",
            "rename",
            "input",
            "urlbuilder",
        ]

    sw_479 = textinput(
        context=context,
        conf={
            "test": {"type": "bool", "value": "true"},
            "debug": {"type": "text", "value": "defunkt"},
            "default": {"type": "text", "value": "defunkt"},
            "prompt": {"type": "text", "value": "Enter Text"},
            "name": {"type": "text", "value": "textinput1"},
            "position": {"type": "int", "value": ""},
        },
    )

    sw_467 = itembuilder(
        context=context,
        conf={
            "attrs": [
                {
                    "value": {"terminal": "attrs_1_value", "type": "text"},
                    "key": {"type": "text", "value": "title"},
                }
            ]
        },
        attrs_1_value=sw_479,
    )

    sw_61 = loop(
        sw_467,
        context=context,
        embed=urlbuilder,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "api"},
            "emit": {"type": "bool", "value": "false"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "urlbuilder",
                    "id": "sw-72",
                    "conf": {
                        "BASE": {
                            "type": "text",
                            "value": "https://api.github.com/search/users",
                        },
                        "PARAM": [
                            {
                                "value": {"type": "text", "subkey": "title"},
                                "key": {"type": "text", "value": "q"},
                            }
                        ],
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_142 = loop(
        sw_61,
        context=context,
        embed=fetchdata,
        conf={
            "count": {"type": "text", "value": "first"},
            "assign": {"type": "text", "value": "info"},
            "emit": {"type": "bool", "value": "false"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "fetchdata",
                    "id": "sw-150",
                    "conf": {
                        "URL": {"type": "url", "subkey": "api"},
                        "path": {"type": "text", "value": "items"},
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_351 = rename(
        sw_142,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "info.user_view_type"},
                    "copy": {"type": "bool", "value": "true"},
                    "newval": {"type": "text", "value": "description"},
                }
            ]
        },
    )

    return sw_351


if __name__ == "__main__":
    pipeline = pipe_125e9fe8bb5f84526d21bebfec3ad116(Context())

    for i in pipeline:
        print(i)
