# Pipe pipe_404411a8d22104920f3fc1f428f33642 generated by pipe2py

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.fetch import pipe as fetch
from riko.modules.count import pipe as count
from riko.modules.truncate import pipe as truncate


def pipe_404411a8d22104920f3fc1f428f33642(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return ["pipecount", "pipefetch", "pipeoutput", "pipetruncate"]

    sw_502 = fetch(
        context,
        conf={
            "URL": {
                "type": "url",
                "value": "file://data/feeds.delicious.com_v2_rss_popular?count=15.xml",
            }
        },
    )

    sw_561 = fetch(
        context,
        conf={
            "URL": {
                "type": "url",
                "value": "file://data/feeds.delicious.com_v2_rss_popular?count=3.xml",
            }
        },
    )

    sw_569 = count(context, sw_561, conf={})

    sw_583 = truncate(
        context,
        sw_502,
        count=sw_569,
        conf={"count": {"terminal": "count", "type": "number"}},
    )

    return sw_583


if __name__ == "__main__":
    pipeline = pipe_404411a8d22104920f3fc1f428f33642(Context())

    for i in pipeline:
        print i
