# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_gigs generated by riko

from riko import Context
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.filter import pipe as _filter
from riko.modules.sort import pipe as sort
from riko.modules.uniq import pipe as uniq
from riko.types.general import Conf
from riko.types.modules import FetchDataRawConf, FilterRawConf, SortRawConf, UniqRawConf


def pipe_gigs(item=None, conf: Conf = None, context: Context | None = None, **kwargs):
    if context and context.describe_input:
        result = []
    elif context and context.describe_dependencies:
        result = ["fetchdata", "filter", "sort", "uniq"]
    else:
        sw_1 = fetchdata(
            None,
            conf=FetchDataRawConf(
                {
                    "url": {"type": "url", "value": "file://riko/data/gigs.json"},
                    "path": {"type": "text", "value": "value.items"},
                }
            ),
            context=context,
        )
        sw_2 = uniq(
            sw_1,
            conf=UniqRawConf({"uniq_key": {"type": "text", "value": "link"}}),
            context=context,
        )
        sw_3 = _filter(
            sw_2,
            conf=FilterRawConf(
                {
                    "combine": {"type": "text", "value": "or"},
                    "permit": {"type": "bool", "value": False},
                    "rule": [
                        {
                            "field": {"type": "text", "value": "title"},
                            "value": {"type": "text", "value": "php"},
                            "op": {"type": "text", "value": "contains"},
                        }
                    ],
                }
            ),
            context=context,
        )
        sw_4 = sort(
            sw_3,
            conf=SortRawConf(
                {
                    "rule": [
                        {
                            "field": {"type": "text", "value": "pubDate"},
                            "dir": {"type": "text", "value": "DESC"},
                        }
                    ]
                }
            ),
            context=context,
        )
        _OUTPUT = sw_4
        result = _OUTPUT

    return result


if __name__ == "__main__":
    for i in pipe_gigs():
        print(i)
