# Pipe pipe_9420a757a49ddf11d8b98349abb5bcf4 generated by pipe2py

from riko import Context
from riko.modules.fetchpage import pipe as fetchpage
from riko.modules.truncate import pipe as truncate


def pipe_9420a757a49ddf11d8b98349abb5bcf4(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return ["pipefetchpage", "pipeoutput", "pipetruncate"]

    sw_266 = fetchpage(
        context,
        conf={
            "URL": {
                "type": "url",
                "value": "file://data/www.caltrain.com_Fares_farechart.html",
            },
            "to": {"type": "text", "value": "</tr>"},
            "token": {"type": "text", "value": '<td style="TEXT-ALIGN: center">'},
            "from": {"type": "text", "value": "One Way</span>"},
        },
    )

    sw_287 = truncate(
        context, sw_266, conf={"count": {"type": "number", "value": "100"}}
    )

    return sw_287


if __name__ == "__main__":
    pipeline = pipe_9420a757a49ddf11d8b98349abb5bcf4(Context())

    for i in pipeline:
        print i
