# Pipe pipe_06c4c44316efb0f5f16e4e7fa4589ba2 generated by pipe2py

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.sort import pipe as sort
from riko.modules.numberinput import pipe as numberinput
from riko.modules.tail import pipe as tail


def pipe_06c4c44316efb0f5f16e4e7fa4589ba2(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [
            (
                "",
                "numberinput1",
                "How many items do you want in the feed?",
                "number",
                "5",
            )
        ]

    if context and context.describe_dependencies:
        return ["pipefetch", "pipenumberinput", "pipeoutput", "pipesort", "pipetail"]

    sw_123 = fetch(
        context,
        conf={
            "URL": {
                "type": "url",
                "value": "file://data/news.yahoo.com_rss_topstories.xml",
            }
        },
    )

    sw_135 = sort(
        context,
        sw_123,
        conf={
            "KEY": [
                {
                    "field": {"type": "text", "value": "title"},
                    "dir": {"type": "text", "value": "DESC"},
                }
            ]
        },
    )

    sw_131 = numberinput(
        context,
        conf={
            "debug": {"type": "number", "value": ""},
            "default": {"type": "number", "value": "5"},
            "prompt": {
                "type": "text",
                "value": "How many items do you want in the feed?",
            },
            "name": {"type": "text", "value": "numberinput1"},
            "position": {"type": "number", "value": ""},
        },
    )

    sw_106 = tail(
        context,
        sw_135,
        count=sw_131,
        conf={"count": {"terminal": "count", "type": "number"}},
    )

    return sw_106


if __name__ == "__main__":
    pipeline = pipe_06c4c44316efb0f5f16e4e7fa4589ba2(Context())

    for i in pipeline:
        print i
