# Pipe pipe_bd0834cfe6cdacb0bea5569505d330b8 generated by pipe2py

from pipe2py import Context
from pipe2py.modules.pipeforever import pipe_forever
from pipe2py.modules.pipetextinput import pipe_textinput
from pipe2py.modules.pipeurlbuilder import pipe_urlbuilder
from pipe2py.modules.pipefetchdata import pipe_fetchdata
from pipe2py.modules.pipeoutput import pipe_output


def pipe_bd0834cfe6cdacb0bea5569505d330b8(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [(u'', u'gid', u'MP Guardian ID', u'text', u'1276')]

    if context and context.describe_dependencies:
        return [u'pipefetchdata', u'pipeoutput', u'pipetextinput', u'pipeurlbuilder']

    forever = pipe_forever()

    sw_606 = pipe_textinput(
        context, forever, conf={'debug': {'type': 'text', 'value': ''}, 'default': {'type': 'text', 'value': '1276'}, 'prompt': {'type': 'text', 'value': 'MP Guardian ID'}, 'name': {'type': 'text', 'value': 'gid'}, 'position': {'type': 'number', 'value': ''}})

    sw_579 = pipe_urlbuilder(
        context, forever, _1_PATH=sw_606, conf={'PATH': [{'terminal': '1_PATH', 'type': 'text'}, {'type': 'text', 'value': 'json'}], 'BASE': {'type': 'text', 'value': ''}, 'PARAM': [{'value': {'type': 'text', 'value': ''}, 'key': {'type': 'text', 'value': ''}}]})

    sw_610 = pipe_fetchdata(
        context, forever, URL=sw_579, conf={'URL': {'terminal': 'URL', 'type': 'url'}, 'path': {'type': 'text', 'value': 'person'}})

    _OUTPUT = pipe_output(
        context, sw_610, conf={})

    return _OUTPUT


if __name__ == "__main__":
    pipeline = pipe_bd0834cfe6cdacb0bea5569505d330b8(Context())

    for i in pipeline:
        print i
