# Pipe pipe_975789b47f17690a21e89b10a702bcbd generated by pipe2py

from riko import Context
from riko.modules.filter import pipe as _filter
from riko.modules.input import pipe as textinput
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.loop import pipe as loop
from riko.modules.regex import pipe as regex
from riko.modules.rename import pipe as rename
from riko.modules.tokenizer import pipe as tokenizer


def pipe_975789b47f17690a21e89b10a702bcbd(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [
            ("", "q", "Status update", "text", "Here's #: some #hashtags to play #with")
        ]

    if context and context.describe_dependencies:
        return [
            "filter",
            "itembuilder",
            "loop",
            "regex",
            "rename",
            "tokenizer",
            "input",
        ]

    sw_417 = textinput(
        context=context,
        conf={
            "test": {"type": "bool", "value": "true"},
            "debug": {"type": "text", "value": ""},
            "default": {
                "type": "text",
                "value": "Here's #: some #hashtags to play #with",
            },
            "prompt": {"type": "text", "value": "Status update"},
            "name": {"type": "text", "value": "q"},
        },
    )

    sw_424 = itembuilder(
        context=context,
        conf={
            "attrs": [
                {
                    "value": {"terminal": "attrs_1_value", "type": "text"},
                    "key": {"type": "text", "value": "title"},
                }
            ]
        },
        attrs_1_value=sw_417,
    )

    sw_436 = _filter(
        sw_424,
        context=context,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "PERMIT": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "title"},
                    "value": {"type": "text", "value": "#"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_447 = loop(
        sw_436,
        embed=regex,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": [
                        {
                            "field": {"type": "text", "value": "title"},
                            "singlematch": {"type": "bool", "value": False},
                            "match": {"type": "text", "value": " [^#]*"},
                            "replace": {"type": "text", "value": " "},
                        },
                        {
                            "field": {"type": "text", "value": "title"},
                            "match": {"type": "text", "value": "^[^#]*"},
                            "replace": {"type": "text", "value": ""},
                        },
                    ]
                },
            },
        },
    )

    sw_470 = loop(
        sw_447,
        context=context,
        embed=tokenizer,
        conf={
            "count": {"type": "text", "value": "all"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "tokenizer",
                    "id": "sw-478",
                    "emit": True,
                    "assign": "loop:tokenizer",
                    "field": "title",
                    "conf": {"delimiter": {"type": "text", "value": " "}},
                },
            },
            "field": {"type": "text", "value": "title"},
        },
    )

    sw_490 = _filter(
        sw_470,
        context=context,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "PERMIT": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "content"},
                    "value": {"type": "text", "value": "#[\\w]"},
                    "op": {"type": "text", "value": "matches"},
                }
            ],
        },
    )

    sw_501 = loop(
        sw_490,
        embed=rename,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": [
                        {
                            "field": {"type": "text", "value": "content"},
                            "copy": {"type": "bool", "value": False},
                            "newval": {"type": "text", "value": "title"},
                        }
                    ]
                },
            },
        },
    )

    return sw_501


if __name__ == "__main__":
    pipeline = pipe_975789b47f17690a21e89b10a702bcbd(Context())

    for i in pipeline:
        print(i)
