# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_b96287458de001ad62a637095df33ad5 generated by riko

from riko import Context
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.strconcat import pipe as strconcat
from riko.modules.union import pipe as union
from riko.types.general import Conf
from riko.types.modules import ItemBuilderRawConf, StrconcatRawConf


def pipe_b96287458de001ad62a637095df33ad5(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        result = []
    elif context and context.describe_dependencies:
        result = ["itembuilder", "strconcat", "union"]
    else:
        sw_605 = strconcat(
            None,
            conf=StrconcatRawConf({"part": {"type": "text", "value": "extVal"}}),
            emit=True,
            context=context,
        )
        sw_632 = itembuilder(
            None,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "ATTR1"},
                            "value": {"type": "text", "value": "VAL1"},
                        },
                        {
                            "key": {"type": "text", "value": "attrpath.attr2"},
                            "value": {"type": "text", "value": "VAL2"},
                        },
                    ]
                }
            ),
            context=context,
        )
        sw_551 = itembuilder(
            None,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "attr1"},
                            "value": {"type": "text", "value": "val1"},
                        },
                        {
                            "key": {"type": "text", "value": "attrpath.attr2"},
                            "value": {"type": "text", "value": "val2"},
                        },
                        {
                            "key": {"type": "text", "value": "attrpath.attr3"},
                            "value": {"terminal": "attrs_3_value", "type": "text"},
                        },
                        {
                            "key": {"type": "text", "value": "longpath.attrpath.attr3"},
                            "value": {"type": "text", "value": "val3"},
                        },
                    ]
                }
            ),
            context=context,
            attrs_3_value=sw_605,
        )
        sw_613 = union(sw_551, conf={}, context=context, OTHERS=[sw_632])
        _OUTPUT = sw_613
        result = _OUTPUT

    return result


if __name__ == "__main__":
    for i in pipe_b96287458de001ad62a637095df33ad5():
        print(i)
