# Pipe pipe_e65397e116d7754da0dd23425f1f0af1 generated by pipe2py

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.loop import pipe as loop
from riko.modules.regex import pipe as regex
from riko.modules.rename import pipe as rename
from riko.modules.urlbuilder import pipe as urlbuilder


def pipe_e65397e116d7754da0dd23425f1f0af1(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "fetch",
            "loop",
            "regex",
            "rename",
            "urlbuilder",
        ]

    sw_565 = fetch(context=context, conf={"URL": {"type": "url", "value": ""}})

    sw_626 = loop(
        sw_565,
        context=context,
        embed=urlbuilder,
        conf={
            "count": {"type": "text", "value": "all"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "urlbuilder",
                    "id": "sw-634",
                    "assign": "media:content.url",
                    "emit": False,
                    "conf": {
                        "PATH": {"type": "text", "value": ""},
                        "BASE": {"type": "text", "value": ""},
                        "PARAM": [
                            {
                                "value": {"type": "text", "value": "qr"},
                                "key": {"type": "text", "value": "cht"},
                            },
                            {
                                "value": {"type": "text", "value": "200x200"},
                                "key": {"type": "text", "value": "chs"},
                            },
                            {
                                "value": {"type": "text", "subkey": "link"},
                                "key": {"type": "text", "value": "chl"},
                            },
                        ],
                    },
                },
            },
        },
    )

    sw_592 = loop(
        sw_626,
        embed=rename,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": [
                        {
                            "field": {"type": "text", "value": "media:content.url"},
                            "copy": {"type": "bool", "value": True},
                            "newval": {"type": "text", "value": "description"},
                        }
                    ]
                },
            },
        },
    )

    sw_636 = loop(
        sw_592,
        embed=regex,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": [
                        {
                            "field": {"type": "text", "value": "description"},
                            "match": {"type": "text", "value": "(.*)"},
                            "replace": {
                                "type": "text",
                                "value": '<img src="$1" alt="QRcode" /><br/>${title}',
                            },
                        }
                    ]
                },
            },
        },
    )

    return sw_636


if __name__ == "__main__":
    pipeline = pipe_e65397e116d7754da0dd23425f1f0af1(Context())

    for i in pipeline:
        print(i)
