# Pipe pipe_188eca77fd28c96c559f71f5729d91ec generated by pipe2py

from riko import Context, get_path
from riko.modules.fetchpage import pipe as fetchpage
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.loop import pipe as loop
from riko.modules.truncate import pipe as truncate


def pipe_188eca77fd28c96c559f71f5729d91ec(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "fetchpage",
            "itembuilder",
            "loop",
            "truncate",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_119(item=None, context=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return fetchpage(
            item,
            context=context,
            conf={
                "URL": {"type": "url", "subkey": "url"},
                "to": {"type": "text", "value": "</tr>"},
                "token": {"type": "text", "value": '<td style="TEXT-ALIGN: center">'},
                "from": {"type": "text", "value": "One Way</span>"},
            },
            **kwargs
        )

    sw_163 = itembuilder(
        context=context,
        conf={
            "attrs": {
                "value": {
                    "type": "text",
                    "value": get_path("www.caltrain.com_Fares_farechart.html"),
                },
                "key": {"type": "text", "value": "url"},
            }
        },
    )

    sw_111 = loop(
        sw_163,
        context=context,
        embed=pipe_sw_119,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "loop:fetchpage"},
            "emit": {"type": "bool", "value": True},
            "embed": {
                "type": "module",
                "value": {
                    "type": "fetchpage",
                    "id": "sw-119",
                    "conf": {
                        "URL": {"type": "url", "subkey": "url"},
                        "to": {"type": "text", "value": "</tr>"},
                        "token": {
                            "type": "text",
                            "value": '<td style="TEXT-ALIGN: center">',
                        },
                        "from": {"type": "text", "value": "One Way</span>"},
                    },
                },
            },
            "with": {"type": "text", "value": ""},
        },
    )

    sw_287 = truncate(
        sw_111, context=context, conf={"count": {"type": "int", "value": "100"}}
    )

    return sw_287


if __name__ == "__main__":
    pipeline = pipe_188eca77fd28c96c559f71f5729d91ec(Context())

    for i in pipeline:
        print(i)
