# Pipe pipe_6e30c269a69baf92cd420900b0645f88 generated by pipe2py

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch
from riko.modules.loop import pipe as loop
from riko.modules.union import pipe as union
from riko.modules.uniq import pipe as uniq
from riko.modules.filter import pipe as _filter
from riko.modules.rename import pipe as rename
from riko.modules.regex import pipe as regex
from riko.modules.sort import pipe as sort


def pipe_6e30c269a69baf92cd420900b0645f88(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "fetch",
            "filter",
            "regex",
            "rename",
            "sort",
            "union",
            "uniq",
        ]

    sw_135 = fetch(
        context=context,
        conf={
            "URL": {
                "type": "url",
                "value": get_path("rss.sueddeutsche.de_rss_Topthemen.xml"),
            }
        },
    )

    sw_233 = fetch(
        context=context,
        conf={
            "URL": {
                "type": "url",
                "value": get_path("rss.sueddeutsche.de_rss_Politik.xml"),
            }
        },
    )

    sw_154 = union(context=context, OTHERS=[sw_233, sw_135], conf={})

    sw_173 = uniq(sw_154, context=context, conf={"uniq_key": {"type": "text", "value": "title"}})

    sw_180 = _filter(
        sw_173,
        context=context,
        conf={
            "COMBINE": {"type": "text", "value": "or"},
            "PERMIT": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "link"},
                    "value": {"type": "text", "value": "sz.de"},
                    "op": {"type": "text", "value": "contains"},
                },
                {
                    "field": {"type": "text", "value": "title"},
                    "value": {"type": "text", "value": "Poroschenko"},
                    "op": {"type": "text", "value": "contains"},
                },
            ],
        },
    )

    sw_210 = loop(
        sw_180,
        embed=rename,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": [
                        {
                            "field": {"type": "text", "value": "y:id.value"},
                            "copy": {"type": "bool", "value": True},
                            "newval": {"type": "text", "value": "link"},
                        }
                    ]
                },
            },
        },
    )

    sw_195 = loop(
        sw_210,
        embed=regex,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": [
                        {
                            "singlelinematch": {"type": "bool", "value": True},
                            "singlematch": {"type": "bool", "value": False},
                            "replace": {"type": "text", "value": ""},
                            "field": {"type": "text", "value": "description"},
                            "casematch": {"type": "bool", "value": True},
                            "match": {"type": "text", "value": "</div>.*$"},
                        },
                        {
                            "field": {"type": "text", "value": "link"},
                            "match": {"type": "text", "value": "^(.*\\/.*)\\/"},
                            "replace": {"type": "text", "value": "$1/2.220/"},
                        },
                    ]
                },
            },
        },
    )

    sw_191 = sort(
        sw_195,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "pubDate"},
                    "dir": {"type": "text", "value": "DESC"},
                }
            ]
        },
    )

    return sw_191


if __name__ == "__main__":
    pipeline = pipe_6e30c269a69baf92cd420900b0645f88(Context())

    for i in pipeline:
        print(i)
