# Pipe pipe_a08134746e30a6dd3a7cb3c0cf098692 generated by pipe2py

from riko import Context
from riko.modules.loop import pipe as loop
from riko.modules.rename import pipe as rename
from riko.modules.strconcat import pipe as strconcat
from riko.modules.xpathfetchpage import pipe as xpathfetchpage

# from riko.modules.createrss import pipe as createrss


def pipe_a08134746e30a6dd3a7cb3c0cf098692(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            # "createrss",
            "loop",
            "rename",
            "strconcat",
            "xpathfetchpage",
        ]

    sw_327 = xpathfetchpage(
        context=context,
        conf={
            "URL": {"type": "url", "value": "http://pinterest.com/popular/"},
            "xpath": {"type": "text", "value": "//a[@class='PinImage ImgLink']"},
        },
    )

    sw_507 = loop(
        sw_327,
        context=context,
        embed=strconcat,
        conf={
            "count": {"type": "text", "value": "all"},
            "embed": {
                "type": "module",
                "value": {
                    "type": "strconcat",
                    "id": "sw-515",
                    "assign": "description",
                    "emit": False,
                    "conf": {
                        "part": [
                            {"type": "text", "value": '<img src="'},
                            {"type": "text", "subkey": "img.src"},
                            {"type": "text", "value": '">'},
                        ]
                    },
                },
            },
        },
    )

    sw_303 = loop(
        sw_507,
        embed=rename,
        context=context,
        conf={
            "count": "all",
            "embed": {
                "emit": True,
                "conf": {
                    "RULE": {
                        "field": {"type": "text", "value": "href"},
                        "copy": {"type": "bool", "value": False},
                        "newval": {"type": "text", "value": "link"},
                    }
                },
            },
        },
    )

    # sw_443 = createrss(
    #     context=context,
    #     sw_303,
    #     conf={
    #         "mediaContentHeight": {"type": "text", "value": ""},
    #         "mediaThumbURL": {"type": "text", "value": ""},
    #         "mediaContentType": {"type": "text", "value": ""},
    #         "description": {"type": "text", "value": ""},
    #         "pubdate": {"type": "text", "value": ""},
    #         "author": {"type": "text", "value": ""},
    #         "title": {"type": "text", "value": "img.alt"},
    #         "mediaThumbHeight": {"type": "text", "value": ""},
    #         "link": {"type": "text", "value": ""},
    #         "mediaContentWidth": {"type": "text", "value": ""},
    #         "mediaContentURL": {"type": "text", "value": "img.src"},
    #         "guid": {"type": "text", "value": ""},
    #         "mediaThumbWidth": {"type": "text", "value": ""},
    #     },
    # )

    return sw_303


if __name__ == "__main__":
    pipeline = pipe_a08134746e30a6dd3a7cb3c0cf098692(Context())

    for i in pipeline:
        print(i)
