# Pipe pipe_80fb3dfc08abfa7e27befe9306fc3ded generated by pipe2py

from pipe2py import Context
from pipe2py.modules.pipeforever import pipe_forever
from pipe2py.modules.pipeyql import pipe_yql
from pipe2py.modules.piperename import pipe_rename
from pipe2py.modules.pipeoutput import pipe_output

def pipe_80fb3dfc08abfa7e27befe9306fc3ded(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context.describe_input:
        return []

    forever = pipe_forever()


    sw_551 = pipe_yql(
        context, forever, conf=dict(raw=dict(type='text', value='results'), envURL=dict(type='text', value='store://datatables.org/alltableswithkeys'), yqlquery=dict(type='text', value='select * from html where url="http://finance.yahoo.com/q?s=yhoo" and xpath=\'//div[@id="yfi_headlines"]/div[2]/ul/li\'')))

    sw_566 = pipe_rename(
        context, sw_551, conf=dict(RULE=[dict(newval=dict(type='text', value='title'), field=dict(type='text', value='a.content'), op=dict(type='text', value='copy'))]))

    _OUTPUT = pipe_output(
        context, sw_566, conf=dict())

    return _OUTPUT


if __name__ == "__main__":
    context = Context()
    pipeline = pipe_80fb3dfc08abfa7e27befe9306fc3ded(context, None)

    for i in pipeline:
        print i