# Pipe pipe_975789b47f17690a21e89b10a702bcbd generated by pipe2py

from riko import Context
from riko.modules.stringtokenizer import pipe as stringtokenizer
from riko.modules.textinput import pipe as textinput
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.filter import pipe as filter
from riko.modules.regex import pipe as regex
from riko.modules.loop import pipe as loop
from riko.modules.filter import pipe as filter
from riko.modules.rename import pipe as rename


def pipe_975789b47f17690a21e89b10a702bcbd(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [
            ("", "q", "Status update", "text", "Here's #: some #hashtags to play #with")
        ]

    if context and context.describe_dependencies:
        return [
            "pipefilter",
            "pipeitembuilder",
            "pipeloop",
            "pipeoutput",
            "piperegex",
            "piperename",
            "pipestringtokenizer",
            "pipetextinput",
        ]

    # We need to wrap submodules (used by loops) so we can pass the
    # input at runtime (as we can to subpipelines)
    def pipe_sw_478(context=None, item=None, conf=None, **kwargs):
        # todo: insert submodule description here
        return pipe_stringtokenizer(
            context, _INPUT, conf={"to-str": {"type": "text", "value": " "}}
        )

    sw_417 = textinput(
        context,
        conf={
            "debug": {"type": "text", "value": ""},
            "default": {
                "type": "text",
                "value": "Here's #: some #hashtags to play #with",
            },
            "prompt": {"type": "text", "value": "Status update"},
            "name": {"type": "text", "value": "q"},
            "position": {"type": "number", "value": ""},
        },
    )

    sw_424 = itembuilder(
        context,
        conf={
            "attrs": [
                {
                    "value": {"terminal": "attrs_1_value", "type": "text"},
                    "key": {"type": "text", "value": "title"},
                }
            ]
        },
        attrs_1_value=sw_417,
    )

    sw_436 = filter(
        context,
        sw_424,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "permit": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "title"},
                    "value": {"type": "text", "value": "#"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_447 = regex(
        context,
        sw_436,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "title"},
                    "globalmatch": {"type": "text", "value": "1"},
                    "match": {"type": "text", "value": " [^#]*"},
                    "replace": {"type": "text", "value": " "},
                },
                {
                    "field": {"type": "text", "value": "title"},
                    "match": {"type": "text", "value": "^[^#]*"},
                    "replace": {"type": "text", "value": ""},
                },
            ]
        },
    )

    sw_470 = loop(
        context,
        sw_447,
        embed=pipe_sw_478,
        conf={
            "count": {"type": "text", "value": "all"},
            "assign": {"type": "text", "value": "loop:stringtokenizer"},
            "emit": {"type": "bool", "value": True},
            "embed": {
                "type": "module",
                "value": {
                    "type": "stringtokenizer",
                    "id": "sw-478",
                    "conf": {"to-str": {"type": "text", "value": " "}},
                },
            },
            "with": {"type": "text", "value": "title"},
        },
    )

    sw_490 = filter(
        context,
        sw_470,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "permit": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "content"},
                    "value": {"type": "text", "value": "#[\\w]"},
                    "op": {"type": "text", "value": "matches"},
                }
            ],
        },
    )

    sw_501 = rename(
        context,
        sw_490,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "content"},
                    "op": {"type": "text", "value": "rename"},
                    "newval": {"type": "text", "value": "title"},
                }
            ]
        },
    )

    return sw_501


if __name__ == "__main__":
    pipeline = pipe_975789b47f17690a21e89b10a702bcbd(Context())

    for i in pipeline:
        print i
