# Pipe pipe_404411a8d22104920f3fc1f428f33642 generated by pipe2py

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch
from riko.modules.fetch import pipe as fetch
from riko.modules.count import pipe as count
from riko.modules.truncate import pipe as truncate


def pipe_404411a8d22104920f3fc1f428f33642(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return ["count", "fetch", "truncate"]

    sw_502 = fetch(
        context=context,
        conf={
            "URL": {
                "type": "url",
                "value": get_path("feeds.delicious.com_v2_rss_popular?count=15.xml"),
            }
        },
    )

    sw_561 = fetch(
        context=context,
        conf={
            "URL": {
                "type": "url",
                "value": get_path("feeds.delicious.com_v2_rss_popular?count=3.xml"),
            }
        },
    )

    sw_569 = count(sw_561, context=context, conf={})

    sw_583 = truncate(
        sw_502,
        context=context,
        count=sw_569,
        conf={"count": {"terminal": "count", "type": "int"}},
    )

    return sw_583


if __name__ == "__main__":
    pipeline = pipe_404411a8d22104920f3fc1f428f33642(Context())

    for i in pipeline:
        print(i)
