# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_1LNyRuNS3BGdkTKaAsqenA generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.input import pipe as _input
from riko.modules.itembuilder import pipe as itembuilder
from riko.types.modules import InputRawConf, ItemBuilderRawConf


def pipe_1LNyRuNS3BGdkTKaAsqenA(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["input", "itembuilder"]
    else:
        sw_1 = _input(
            item,
            conf=InputRawConf(
                {
                    "test": {"type": "bool", "value": "true"},
                    "name": {"type": "text", "value": "textinput1"},
                    "input_key": {"type": "text", "value": "textinput1"},
                    "prompt": {"type": "text", "value": "Stock Symbol:"},
                    "default": {"type": "text", "value": "yhoo"},
                    "type": {"type": "text", "value": "text"},
                }
            ),
            context=context,
        )
        sw_2 = itembuilder(
            None,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "symbol"},
                            "value": {"terminal": "symbol_in", "type": "text"},
                        }
                    ]
                }
            ),
            context=context,
            symbol_in=sw_1,
        )
        _OUTPUT = sw_2

    return _OUTPUT


mark_subpipe(pipe_1LNyRuNS3BGdkTKaAsqenA, subtype="source")


if __name__ == "__main__":
    for i in pipe_1LNyRuNS3BGdkTKaAsqenA():
        print(i)
