# Pipe pipe_eb3e27f8f1841835fdfd279cd96ff9d8 generated by pipe2py

from riko import Context, get_path
from riko.modules.urlinput import pipe as urlinput
from riko.modules.fetchdata import pipe as fetchdata
from riko.modules.input import pipe as textinput
from riko.modules.filter import pipe as _filter
from riko.modules.rename import pipe as rename
from riko.modules.regex import pipe as regex


def pipe_eb3e27f8f1841835fdfd279cd96ff9d8(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [
            ("", "q", "Caption search term", "text", "maverick"),
            (
                "",
                "url",
                "Caption URL",
                "url",
                get_path("rsc-ne-scotland.org.uk_mashe_ititle_xml_jisc10bean.xml"),
            ),
        ]

    if context and context.describe_dependencies:
        return [
            "fetchdata",
            "filter",
            "regex",
            "rename",
            "input",
            "urlinput",
        ]

    sw_521 = urlinput(
        context=context,
        conf={
            "debug": {"type": "url", "value": ""},
            "default": {
                "type": "url",
                "value": get_path("rsc-ne-scotland.org.uk_mashe_ititle_xml_jisc10bean.xml"),
            },
            "prompt": {"type": "text", "value": "Caption URL"},
            "name": {"type": "text", "value": "url"},
            "position": {"type": "int", "value": ""},
        },
    )

    sw_572 = fetchdata(
        context=context,
        URL=sw_521,
        conf={
            "URL": {"terminal": "URL", "type": "url"},
            "path": {"type": "text", "value": "body.div.p"},
        },
    )

    sw_621 = textinput(
        context=context,
        conf={
            "debug": {"type": "text", "value": ""},
            "default": {"type": "text", "value": "maverick"},
            "prompt": {"type": "text", "value": "Caption search term"},
            "name": {"type": "text", "value": "q"},
            "position": {"type": "int", "value": ""},
        },
    )

    sw_584 = _filter(
        sw_572,
        context=context,
        RULE_1_value=sw_621,
        conf={
            "COMBINE": {"type": "text", "value": "and"},
            "EMIT": {"type": "bool", "value": True},
            "RULE": [
                {
                    "field": {"type": "text", "value": "content"},
                    "value": {"terminal": "RULE_1_value", "type": "text"},
                    "op": {"type": "text", "value": "contains"},
                }
            ],
        },
    )

    sw_595 = rename(
        sw_584,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "begin"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "ctime"},
                },
                {
                    "field": {"type": "text", "value": "content"},
                    "op": {"type": "text", "value": "copy"},
                    "newval": {"type": "text", "value": "title"},
                },
            ]
        },
    )

    sw_606 = regex(
        sw_595,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "ctime"},
                    "match": {"type": "text", "value": "(.*)"},
                    "replace": {"type": "text", "value": "&time=$1"},
                }
            ]
        },
    )

    return sw_606


if __name__ == "__main__":
    pipeline = pipe_eb3e27f8f1841835fdfd279cd96ff9d8(Context())

    for i in pipeline:
        print(i)
