# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_2de0e4517ed76082dcddf66f7b218057 generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.fetch import pipe as fetch
from riko.types.modules import FetchRawConf


def pipe(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetch"]
    else:
        sw_478 = fetch(
            item,
            conf=FetchRawConf(
                {
                    "url": {
                        "type": "url",
                        "value": "file://riko/data/feeds.feedburner.com_ouseful.xml",
                    }
                }
            ),
            context=context,
        )
        _OUTPUT = sw_478

    return _OUTPUT


mark_subpipe(pipe, subtype="source")


if __name__ == "__main__":
    for i in pipe():
        print(i)
