# Pipe pipe_2de0e4517ed76082dcddf66f7b218057 generated by pipe2py

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch


def pipe_2de0e4517ed76082dcddf66f7b218057(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}
    print("pipe_2de0e4517ed76082dcddf66f7b218057!")

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return ["fetch"]

    sw_478 = fetch(
        context=context, conf={"URL": get_path("feeds.feedburner.com_ouseful.xml")}
    )

    return sw_478


if __name__ == "__main__":
    pipeline = pipe_2de0e4517ed76082dcddf66f7b218057(Context())

    for i in pipeline:
        print(i)
