# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_HrX5bjkv3BGEp9eSy6ky6g generated by riko

from riko import Context
from riko.modules.feedautodiscovery import pipe as feedautodiscovery
from riko.modules.fetch import pipe as fetch
from riko.modules.loop import pipe as loop
from riko.modules.sort import pipe as sort
from riko.modules.truncate import pipe as truncate
from riko.types.general import Conf
from riko.types.modules import (
    FeedAutoDiscoveryRawConf,
    FetchRawConf,
    LoopRawConf,
    SortRawConf,
    TruncateRawConf,
)


def pipe_HrX5bjkv3BGEp9eSy6ky6g(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        result = []
    elif context and context.describe_dependencies:
        result = ["feedautodiscovery", "loop", "sort", "truncate"]
    else:
        sw_149 = feedautodiscovery(
            None,
            conf=FeedAutoDiscoveryRawConf(
                {"url": {"type": "url", "value": "file://riko/data/edition.cnn.html"}}
            ),
            context=context,
        )
        sw_157 = loop(
            sw_149,
            conf=LoopRawConf(
                {
                    "count": {"type": "text", "value": "all"},
                    "embed": {
                        "type": "module",
                        "value": {
                            "conf": FetchRawConf(
                                {"url": {"subkey": "link", "type": "url"}}
                            ),
                            "id": "sw-165",
                            "type": "fetch",
                            "emit": {"type": "bool", "value": True},
                            "assign": {"type": "text", "value": "loop:fetch"},
                        },
                    },
                }
            ),
            context=context,
            embed=fetch,
        )
        sw_174 = sort(
            sw_157,
            conf=SortRawConf(
                {
                    "rule": [
                        {
                            "dir": {"type": "text", "value": "ASC"},
                            "field": {"type": "text", "value": "pubDate"},
                            "type": "datetime",
                        }
                    ]
                }
            ),
            context=context,
        )
        sw_191 = truncate(
            sw_174,
            conf=TruncateRawConf({"count": {"type": "number", "value": "25"}}),
            context=context,
        )
        _OUTPUT = sw_191
        result = _OUTPUT

    return result


if __name__ == "__main__":
    for i in pipe_HrX5bjkv3BGEp9eSy6ky6g():
        print(i)
