# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_551507461cbcb19a828165daad5fe007 generated by riko

from riko import Context
from riko.modules.fetchsitefeed import pipe as fetchsitefeed
from riko.modules.input import pipe as _input
from riko.modules.truncate import pipe as truncate
from riko.types.general import Conf
from riko.types.modules import FetchSiteFeedRawConf, InputRawConf, TruncateRawConf


def pipe_551507461cbcb19a828165daad5fe007(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        _OUTPUT = [
            (
                "",
                "urlinput1",
                "Enter a URL",
                "url",
                "file://riko/data/www.bbc.co.uk_news.html",
            )
        ]
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetchsitefeed", "input", "truncate"]
    else:
        sw_242 = _input(
            None,
            conf=InputRawConf(
                {
                    "debug": {
                        "type": "url",
                        "value": "file://riko/data/www.bbc.co.uk_news.html",
                    },
                    "default": {
                        "type": "url",
                        "value": "file://riko/data/www.bbc.co.uk_news.html",
                    },
                    "name": {"type": "text", "value": "urlinput1"},
                    "position": {"type": "number", "value": ""},
                    "prompt": {"type": "text", "value": "Enter a URL"},
                }
            ),
            context=context,
        )
        sw_234 = fetchsitefeed(
            None,
            conf=FetchSiteFeedRawConf({"url": {"terminal": "1_URL", "type": "url"}}),
            context=context,
            _1_URL=sw_242,
        )
        sw_246 = truncate(
            sw_234,
            conf=TruncateRawConf({"count": {"type": "number", "value": "5"}}),
            context=context,
        )
        _OUTPUT = sw_246

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_551507461cbcb19a828165daad5fe007():
        print(i)
