# Pipe pipe_58a53262da5a095fe7a0d6d905cc4db6 generated by pipe2py

from riko import Context, get_path
from riko.collections import SyncCollection
from riko.modules.fetch import pipe as fetch
from riko.modules.urlbuilder import pipe as urlbuilder
from riko.modules.union import pipe as union
from riko.modules.sort import pipe as sort
from riko.modules.truncate import pipe as truncate
from riko.modules.reverse import pipe as reverse


def pipe_58a53262da5a095fe7a0d6d905cc4db6(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "fetch",
            "reverse",
            "sort",
            "truncate",
            "union",
            "urlbuilder",
        ]

    sw_550 = SyncCollection(
        [
            {"url": get_path("blog.ouseful.info_feed.xml")},
            {"url": get_path("feeds.feedburner.com_TheEdTechie.xml")},
        ]
    )

    sw_606 = urlbuilder(
        context=context,
        conf={
            "PATH": {"type": "text", "value": ""},
            "BASE": {
                "type": "text",
                "value": get_path("www.greenhughes.com_rssfeed.xml"),
            },
            "PARAM": [
                {
                    "value": {"type": "text", "value": ""},
                    "key": {"type": "text", "value": ""},
                }
            ],
        },
    )

    sw_572 = fetch(
        context=context,
        _1_URL=sw_606,
        conf={"URL": {"terminal": "1_URL", "type": "url"}},
    )

    sw_580 = union(sw_550, context=context, OTHERS=[sw_572], conf={})

    sw_565 = sort(
        sw_580,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "title"},
                    "dir": {"type": "text", "value": "ASC"},
                }
            ]
        },
    )

    sw_596 = truncate(sw_565, context=context, conf={"count": {"type": "int", "value": "3"}})

    sw_625 = reverse(sw_596, context=context, conf={})

    return sw_625


if __name__ == "__main__":
    pipeline = pipe_58a53262da5a095fe7a0d6d905cc4db6(Context())

    for i in pipeline:
        print(i)
