# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_975789b47f17690a21e89b10a702bcbd generated by riko

from riko import Context
from riko.modules.filter import pipe as _filter
from riko.modules.input import pipe as _input
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.regex import pipe as regex
from riko.modules.rename import pipe as rename
from riko.modules.tokenizer import pipe as tokenizer
from riko.types.modules import (
    FilterRawConf,
    InputRawConf,
    ItemBuilderRawConf,
    RegexRawConf,
    RenameRawConf,
    TokenizerRawConf,
)


def pipe_975789b47f17690a21e89b10a702bcbd(
    item=None, context: Context | None = None, **_
):
    if context and context.describe_input:
        _OUTPUT = [
            ("", "q", "Status update", "text", "Here's #: some #hashtags to play #with")
        ]
    elif context and context.describe_dependencies:
        _OUTPUT = ["filter", "input", "itembuilder", "regex", "rename", "tokenizer"]
    else:
        sw_417 = _input(
            item,
            conf=InputRawConf(
                {
                    "debug": {"type": "text", "value": ""},
                    "default": {
                        "type": "text",
                        "value": "Here's #: some #hashtags to play #with",
                    },
                    "name": {"type": "text", "value": "q"},
                    "position": {"type": "float", "value": ""},
                    "prompt": {"type": "text", "value": "Status update"},
                }
            ),
            context=context,
        )
        sw_424 = itembuilder(
            None,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "title"},
                            "value": {"terminal": "attrs_1_value", "type": "text"},
                        }
                    ]
                }
            ),
            context=context,
            attrs_1_value=sw_417,
        )
        sw_436 = _filter(
            sw_424,
            conf=FilterRawConf(
                {
                    "combine": {"type": "text", "value": "and"},
                    "permit": {"type": "bool", "value": True},
                    "rule": [
                        {
                            "field": {"type": "text", "value": "title"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "#"},
                        }
                    ],
                }
            ),
            context=context,
        )
        sw_447 = regex(
            sw_436,
            conf=RegexRawConf(
                {
                    "rule": [
                        {
                            "field": {"type": "text", "value": "title"},
                            "singlematch": {"type": "bool", "value": False},
                            "match": {"type": "text", "value": " [^#]*"},
                            "replace": {"type": "text", "value": " "},
                        },
                        {
                            "field": {"type": "text", "value": "title"},
                            "match": {"type": "text", "value": "^[^#]*"},
                            "replace": {"type": "text", "value": ""},
                        },
                    ]
                }
            ),
            emit=True,
            assign="loop:regex",
            count="all",
            context=context,
        )
        sw_470 = tokenizer(
            sw_447,
            conf=TokenizerRawConf({"delimiter": {"type": "text", "value": " "}}),
            emit=True,
            assign="loop:tokenizer",
            field="title",
            count="all",
            context=context,
        )
        sw_490 = _filter(
            sw_470,
            conf=FilterRawConf(
                {
                    "combine": {"type": "text", "value": "and"},
                    "permit": {"type": "bool", "value": True},
                    "rule": [
                        {
                            "field": {"type": "text", "value": "content"},
                            "op": {"type": "text", "value": "matches"},
                            "value": {"type": "text", "value": "#[\\w]"},
                        }
                    ],
                }
            ),
            context=context,
        )
        sw_501 = rename(
            sw_490,
            conf=RenameRawConf(
                {
                    "rule": [
                        {
                            "field": {"type": "text", "value": "content"},
                            "copy": {"type": "bool", "value": False},
                            "newval": {"type": "text", "value": "title"},
                        }
                    ]
                }
            ),
            emit=True,
            assign="loop:rename",
            count="all",
            context=context,
        )
        _OUTPUT = sw_501

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_975789b47f17690a21e89b10a702bcbd():
        print(i)
