# Pipe pipe_1I75yiUv3BGhgVWjjUnRlg generated by pipe2py

from pipe2py import Context
from pipe2py.modules.pipeforever import pipe_forever
from pipe2py.modules.pipefetch import pipe_fetch
from pipe2py.modules.pipeuniq import pipe_uniq
from pipe2py.modules.pipeoutput import pipe_output

def pipe_1I75yiUv3BGhgVWjjUnRlg(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context.describe_input:
        return []

    forever = pipe_forever()


    sw_61 = pipe_fetch(
        context, forever, conf=dict(URL=dict(type='url', value='file://data/feeds.feedburner.com_yodelanecdotal.xml')))

    sw_72 = pipe_uniq(
        context, sw_61, conf=dict(field=dict(type='text', value='dc:creator')))

    _OUTPUT = pipe_output(
        context, sw_72, conf=dict())

    return _OUTPUT


if __name__ == "__main__":
    context = Context()
    pipeline = pipe_1I75yiUv3BGhgVWjjUnRlg(context, None)

    for i in pipeline:
        print i
