# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_404411a8d22104920f3fc1f428f33642 generated by riko

from riko import Context
from riko.modules.count import pipe as count
from riko.modules.fetch import pipe as fetch
from riko.modules.truncate import pipe as truncate
from riko.types.general import Conf
from riko.types.modules import CountRawConf, FetchRawConf, TruncateRawConf


def pipe_404411a8d22104920f3fc1f428f33642(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["count", "fetch", "truncate"]
    else:
        sw_561 = fetch(
            None,
            conf=FetchRawConf(
                {
                    "url": {
                        "type": "url",
                        "value": "file://riko/data/feeds.delicious.com_v2_rss_popular_count=3.xml",
                    }
                }
            ),
            context=context,
        )
        sw_569 = count(sw_561, conf=CountRawConf({}), emit=True, context=context)
        sw_502 = fetch(
            None,
            conf=FetchRawConf(
                {
                    "url": {
                        "type": "url",
                        "value": "file://riko/data/feeds.delicious.com_v2_rss_popular_count=15.xml",
                    }
                }
            ),
            context=context,
        )
        sw_583 = truncate(
            sw_502,
            conf=TruncateRawConf({"count": {"terminal": "count", "type": "number"}}),
            context=context,
            count=sw_569,
        )
        _OUTPUT = sw_583

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_404411a8d22104920f3fc1f428f33642():
        print(i)
