# Pipe pipe_06c4c44316efb0f5f16e4e7fa4589ba2 generated by pipe2py

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch
from riko.modules.sort import pipe as sort
from riko.modules.input import pipe as numberinput
from riko.modules.tail import pipe as tail


def pipe_06c4c44316efb0f5f16e4e7fa4589ba2(
    context=None, conf=None
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [
            (
                "",
                "numberinput1",
                "How many items do you want in the feed?",
                "number",
                "5",
            )
        ]

    if context and context.describe_dependencies:
        return ["fetch", "numberinput", "sort", "tail"]

    sw_123 = fetch(
        context=context,
        conf={
            "URL": {
                "type": "url",
                "value": get_path("news.yahoo.com_rss_topstories.xml"),
            }
        },
    )

    sw_135 = sort(
        sw_123,
        context=context,
        conf={
            "RULE": [
                {
                    "field": {"type": "text", "value": "title"},
                    "dir": {"type": "text", "value": "DESC"},
                }
            ]
        },
    )

    sw_131 = numberinput(
        context=context,
        conf={
            "test": {"type": "bool", "value": "true"},
            "debug": {"type": "int", "value": ""},
            "default": {"type": "int", "value": "5"},
            "prompt": {
                "type": "text",
                "value": "How many items do you want in the feed?",
            },
            "name": {"type": "text", "value": "numberinput1"},
        },
    )

    sw_106 = tail(
        sw_135,
        context=context,
        count=sw_131,
        conf={"count": {"terminal": "count", "type": "int"}},
    )

    return sw_106


if __name__ == "__main__":
    pipeline = pipe_06c4c44316efb0f5f16e4e7fa4589ba2(Context())

    for i in pipeline:
        print(i)
