# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_188eca77fd28c96c559f71f5729d91ec generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.fetchpage import pipe as fetchpage
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.truncate import pipe as truncate
from riko.types.modules import FetchPageRawConf, ItemBuilderRawConf, TruncateRawConf


def pipe_188eca77fd28c96c559f71f5729d91ec(
    item=None, context: Context | None = None, **_
):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetchpage", "itembuilder", "truncate"]
    else:
        sw_163 = itembuilder(
            item,
            conf=ItemBuilderRawConf(
                {
                    "attrs": {
                        "key": {"type": "text", "value": "url"},
                        "value": {
                            "type": "text",
                            "value": "file://riko/data/www.caltrain.com_Fares_farechart.html",
                        },
                    }
                }
            ),
            context=context,
        )
        sw_111 = fetchpage(
            sw_163,
            conf=FetchPageRawConf(
                {
                    "url": {"subkey": "url", "type": "url"},
                    "start": {"type": "text", "value": "One Way</span>"},
                    "end": {"type": "text", "value": "</tr>"},
                    "token": {
                        "type": "text",
                        "value": '<td style="text-align: center;">',
                    },
                }
            ),
            emit=True,
            assign="loop:fetchpage",
            count="all",
            context=context,
        )
        sw_287 = truncate(
            sw_111,
            conf=TruncateRawConf({"count": {"type": "float", "value": "100"}}),
            context=context,
        )
        _OUTPUT = sw_287

    return _OUTPUT


mark_subpipe(pipe_188eca77fd28c96c559f71f5729d91ec, subtype="source")


if __name__ == "__main__":
    for i in pipe_188eca77fd28c96c559f71f5729d91ec():
        print(i)
