# Pipe pipe_e519dd393f943315f7e4128d19db2eac generated by pipe2py

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.input import pipe as textinput
from riko.modules.urlbuilder import pipe as urlbuilder


def pipe_e519dd393f943315f7e4128d19db2eac(context=None, conf=None):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return [("", "q", "Search term:", "text", "enterprise mashup")]

    if context and context.describe_dependencies:
        return ["fetch", "input", "urlbuilder"]

    sw_552 = textinput(
        context=context,
        conf={
            "test": {"type": "bool", "value": "true"},
            "debug": {"type": "text", "value": ""},
            "default": {"type": "text", "value": "enterprise mashup"},
            "prompt": {"type": "text", "value": "Search term:"},
            "name": {"type": "text", "value": "q"},
        },
    )

    sw_492 = urlbuilder(
        context=context,
        PARAM_5_value=sw_552,
        conf={
            "PATH": {"type": "text", "value": ""},
            "BASE": {"type": "text", "value": "news.google.com/rss"},
            "EXT": {"type": "text", "value": "xml"},
            "PARAM": [
                {
                    "value": {"type": "text", "value": "en-US"},
                    "key": {"type": "text", "value": "hl"},
                },
                {
                    "value": {"type": "text", "value": "US"},
                    "key": {"type": "text", "value": "gl"},
                },
                {
                    "value": {"type": "text", "value": "US:en"},
                    "key": {"type": "text", "value": "ceid"},
                },
                {
                    "value": {"terminal": "PARAM_5_value", "type": "text"},
                    "key": {"type": "text", "value": "q"},
                },
            ],
        },
    )

    sw_481 = fetch(
        context=context,
        _1_URL=sw_492,
        conf={"URL": {"terminal": "1_URL", "type": "url"}, "offline": True},
    )

    return sw_481


if __name__ == "__main__":
    pipeline = pipe_e519dd393f943315f7e4128d19db2eac(Context())

    for i in pipeline:
        print(i)
