# Pipe pipe_b96287458de001ad62a637095df33ad5 generated by pipe2py

from riko import Context
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.strconcat import pipe as strconcat
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.union import pipe as union


def pipe_b96287458de001ad62a637095df33ad5(
    context=None, _INPUT=None, conf=None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return ["pipeitembuilder", "pipeoutput", "pipestrconcat", "pipeunion"]

    sw_632 = itembuilder(
        context,
        conf={
            "attrs": [
                {
                    "value": {"type": "text", "value": "VAL1"},
                    "key": {"type": "text", "value": "ATTR1"},
                },
                {
                    "value": {"type": "text", "value": "VAL2"},
                    "key": {"type": "text", "value": "attrpath.attr2"},
                },
            ]
        },
    )

    sw_605 = strconcat(context, conf={"part": {"type": "text", "value": "extVal"}})

    sw_551 = itembuilder(
        context,
        attrs_3_value=sw_605,
        conf={
            "attrs": [
                {
                    "value": {"type": "text", "value": "val1"},
                    "key": {"type": "text", "value": "attr1"},
                },
                {
                    "value": {"type": "text", "value": "val2"},
                    "key": {"type": "text", "value": "attrpath.attr2"},
                },
                {
                    "value": {"terminal": "attrs_3_value", "type": "text"},
                    "key": {"type": "text", "value": "attrpath.attr3"},
                },
                {
                    "value": {"type": "text", "value": "val3"},
                    "key": {"type": "text", "value": "longpath.attrpath.attr3"},
                },
            ]
        },
    )

    sw_613 = union(context, sw_551, _OTHER1=sw_632, conf={})

    return sw_613


if __name__ == "__main__":
    pipeline = pipe_b96287458de001ad62a637095df33ad5(Context())

    for i in pipeline:
        print i
