# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_testpipe1 generated by riko

from riko import Context
from riko.modules.fetch import pipe as fetch
from riko.modules.filter import pipe as _filter
from riko.types.modules import FetchRawConf, FilterRawConf


def pipe_testpipe1(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetch", "filter"]
    else:
        sw_90 = fetch(
            item,
            conf=FetchRawConf(
                {"url": {"type": "url", "value": "file://riko/data/feed.xml"}}
            ),
            context=context,
        )
        sw_102 = _filter(
            sw_90,
            conf=FilterRawConf(
                {
                    "combine": {"type": "text", "value": "and"},
                    "permit": {"type": "bool", "value": True},
                    "rule": [
                        {
                            "field": {"type": "text", "value": "description"},
                            "op": {"type": "text", "value": "contains"},
                            "value": {"type": "text", "value": "the"},
                        }
                    ],
                }
            ),
            context=context,
        )
        _OUTPUT = sw_102

    return _OUTPUT


if __name__ == "__main__":
    for i in pipe_testpipe1():
        print(i)
