# Pipe pipe_QMrlL_FS3BGlpwryODY80A generated by pipe2py
#
# Hand-maintained: the compiler has no splitter codegen support yet, so the
# `split` tuple-unpacking and output routing below are written by hand. See
# docs/SPLITTER_CODEGEN.md for the plan to generate this automatically.

from riko import Context, get_path
from riko.modules.fetch import pipe as fetch
from riko.modules.filter import pipe as _filter
from riko.modules.loop import pipe as loop
from riko.modules.regex import pipe as regex
from riko.modules.split import pipe as split
from riko.modules.union import pipe as union
from riko.types.general import Conf
from riko.types.modules import FetchRawConf, FilterRawConf, LoopRawConf, RegexRawConf


def pipe_QMrlL_FS3BGlpwryODY80A(
    item=None, conf: Conf = None, context: Context | None = None, **kwargs
):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    if context and context.describe_dependencies:
        return [
            "fetch",
            "filter",
            "regex",
            "split",
            "union",
        ]

    sw_140 = fetch(
        context=context,
        conf=FetchRawConf(
            {
                "url": {
                    "type": "url",
                    "value": get_path("news.yahoo.com_rss_health.xml"),
                }
            }
        ),
    )

    sw_108, sw_109 = split(sw_140, context=context)

    sw_159 = _filter(
        sw_108,
        context=context,
        conf=FilterRawConf(
            {
                "combine": {"type": "text", "value": "and"},
                "permit": {"type": "bool", "value": True},
                "rule": {
                    "field": {"type": "text", "value": "summary"},
                    "value": {"type": "text", "value": "drug"},
                    "op": {"type": "text", "value": "contains"},
                },
            }
        ),
    )

    sw_204 = loop(
        sw_159,
        embed=regex,
        context=context,
        conf=LoopRawConf(
            {
                "count": {"type": "text", "value": "all"},
                "embed": {
                    "type": "module",
                    "value": {
                        "type": "regex",
                        "id": "sw-204e",
                        "emit": {"type": "bool", "value": True},
                        "conf": RegexRawConf(
                            {
                                "rule": {
                                    "field": {"type": "text", "value": "title"},
                                    "match": {"type": "text", "value": "(.+)"},
                                    "replace": {"type": "text", "value": "[Drugs] $1"},
                                }
                            }
                        ),
                    },
                },
            }
        ),
    )

    sw_148 = _filter(
        sw_109,
        context=context,
        conf=FilterRawConf(
            {
                "combine": {"type": "text", "value": "and"},
                "permit": {"type": "bool", "value": True},
                "rule": {
                    "field": {"type": "text", "value": "summary"},
                    "value": {"type": "text", "value": "weight"},
                    "op": {"type": "text", "value": "contains"},
                },
            }
        ),
    )

    sw_189 = loop(
        sw_148,
        embed=regex,
        context=context,
        conf=LoopRawConf(
            {
                "count": {"type": "text", "value": "all"},
                "embed": {
                    "type": "module",
                    "value": {
                        "type": "regex",
                        "id": "sw-189e",
                        "emit": {"type": "bool", "value": True},
                        "conf": RegexRawConf(
                            {
                                "rule": {
                                    "field": {"type": "text", "value": "title"},
                                    "match": {"type": "text", "value": "(.+)"},
                                    "replace": {"type": "text", "value": "[Weight] $1"},
                                }
                            }
                        ),
                    },
                },
            }
        ),
    )

    sw_110 = union(context=context, OTHERS=[sw_204, sw_189], conf=None)

    return sw_110


if __name__ == "__main__":
    pipeline = pipe_QMrlL_FS3BGlpwryODY80A(context=Context())

    for i in pipeline:
        print(i)
