# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_9420a757a49ddf11d8b98349abb5bcf4 generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.fetchpage import pipe as fetchpage
from riko.modules.truncate import pipe as truncate
from riko.types.modules import FetchPageRawConf, TruncateRawConf


def pipe(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["fetchpage", "truncate"]
    else:
        sw_266 = fetchpage(
            item,
            conf=FetchPageRawConf(
                {
                    "url": {
                        "type": "url",
                        "value": "file://riko/data/www.caltrain.com_Fares_farechart.html",
                    },
                    "start": {"type": "text", "value": "One Way</span>"},
                    "end": {"type": "text", "value": "</tr>"},
                    "token": {
                        "type": "text",
                        "value": '<td style="text-align: center;">',
                    },
                }
            ),
            context=context,
        )
        sw_287 = truncate(
            sw_266,
            conf=TruncateRawConf({"count": {"type": "float", "value": "100"}}),
            context=context,
        )
        _OUTPUT = sw_287

    return _OUTPUT


mark_subpipe(pipe, subtype="source")


if __name__ == "__main__":
    for i in pipe():
        print(i)
