# Pipe testpipe1 generated by pipe2py

from pipe2py import Context
from pipe2py.modules.pipeforever import pipe_forever
from pipe2py.modules.pipefetch import pipe_fetch
from pipe2py.modules.pipefilter import pipe_filter
from pipe2py.modules.pipeoutput import pipe_output


def testpipe1(context=None, _INPUT=None, conf=None, **kwargs):
    # todo: insert pipeline description here
    conf = conf or {}

    if context and context.describe_input:
        return []

    forever = pipe_forever()


    sw_90 = pipe_fetch(
        context, forever, conf={'URL': {'type': 'url', 'value': 'file://feed.xml'}})

    sw_102 = pipe_filter(
        context, sw_90, conf={'COMBINE': {'type': 'text', 'value': 'and'}, 'MODE': {'type': 'text', 'value': 'permit'}, 'RULE': [{'field': {'type': 'text', 'value': 'description'}, 'value': {'type': 'text', 'value': 'the'}, 'op': {'type': 'text', 'value': 'contains'}}]})

    _OUTPUT = pipe_output(
        context, sw_102, conf=[])

    return _OUTPUT


if __name__ == "__main__":
    context = Context()
    pipeline = testpipe1(context, None)

    for i in pipeline:
        print i