# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_679e2c544332e978b15b6b163767975f generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.strreplace import pipe as strreplace
from riko.types.modules import ItemBuilderRawConf, StrReplaceRawConf


def pipe(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["itembuilder", "strreplace"]
    else:
        sw_1 = itembuilder(
            item,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "link"},
                            "value": {"type": "text", "value": "www.google.com"},
                        },
                        {
                            "key": {"type": "text", "value": "title"},
                            "value": {"type": "text", "value": "google"},
                        },
                        {
                            "key": {"type": "text", "value": "author"},
                            "value": {"type": "text", "value": "$"},
                        },
                    ]
                }
            ),
            context=context,
        )
        sw_2 = strreplace(
            sw_1,
            conf=StrReplaceRawConf(
                {
                    "rule": [
                        {
                            "find": {"type": "text", "value": "$"},
                            "replace": {"type": "text", "value": "USD"},
                            "param": {"type": "text", "value": "first"},
                        }
                    ]
                }
            ),
            assign="author",
            field="author",
            context=context,
        )
        _OUTPUT = sw_2

    return _OUTPUT


mark_subpipe(pipe, subtype="source")


if __name__ == "__main__":
    for i in pipe():
        print(i)
