# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_a3d1afa31f0a24cc51dcbe79f1590343 generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.regex import pipe as regex
from riko.types.modules import ItemBuilderRawConf, RegexRawConf


def pipe(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["itembuilder", "regex"]
    else:
        sw_1 = itembuilder(
            item,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "url"},
                            "value": {
                                "type": "text",
                                "value": "http://www.caltrain.com/Fares/farechart.html",
                            },
                        }
                    ]
                }
            ),
            context=context,
        )
        sw_2 = regex(
            sw_1,
            conf=RegexRawConf(
                {
                    "rule": [
                        {
                            "field": {"type": "text", "value": "url"},
                            "match": {"type": "text", "value": "http.*html"},
                            "replace": {"type": "text", "value": "farechart"},
                        }
                    ]
                }
            ),
            context=context,
        )
        _OUTPUT = sw_2

    return _OUTPUT


mark_subpipe(pipe, subtype="source")


if __name__ == "__main__":
    for i in pipe():
        print(i)
