# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_4f26297843f4952fad920af5990ddc50 generated by riko

from riko import Context
from riko.modules._subpipe import mark_subpipe
from riko.modules.datebuilder import pipe as datebuilder
from riko.modules.dateformat import pipe as dateformat
from riko.modules.input import pipe as _input
from riko.modules.itembuilder import pipe as itembuilder
from riko.types.modules import DateFormatRawConf, InputRawConf, ItemBuilderRawConf


def pipe(item=None, context: Context | None = None, **_):
    if context and context.describe_input:
        _OUTPUT = []
    elif context and context.describe_dependencies:
        _OUTPUT = ["datebuilder", "dateformat", "input", "itembuilder"]
    else:
        sw_1 = itembuilder(
            item,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "content"},
                            "value": {"type": "text", "value": "12/3/2014"},
                        }
                    ]
                }
            ),
            context=context,
        )
        sw_fmt = _input(
            None,
            conf=InputRawConf(
                {
                    "test": {"type": "bool", "value": "true"},
                    "default": {"type": "text", "value": "%B %d, %Y"},
                    "prompt": {"type": "text", "value": "enter date format"},
                    "name": {"type": "text", "value": "format_input"},
                    "type": {"type": "text", "value": "text"},
                }
            ),
            context=context,
        )
        sw_2 = datebuilder(sw_1, conf={}, assign="date", context=context)
        sw_3 = dateformat(
            sw_2,
            conf=DateFormatRawConf({"format": {"terminal": "format", "type": "text"}}),
            emit=True,
            field="date",
            context=context,
            format=sw_fmt,
        )
        sw_4 = itembuilder(
            None,
            conf=ItemBuilderRawConf(
                {
                    "attrs": [
                        {
                            "key": {"type": "text", "value": "date"},
                            "value": {"terminal": "attrs_1_value", "type": "text"},
                        }
                    ]
                }
            ),
            context=context,
            attrs_1_value=sw_3,
        )
        _OUTPUT = sw_4

    return _OUTPUT


mark_subpipe(pipe, subtype="source")


if __name__ == "__main__":
    for i in pipe():
        print(i)
