# vim: sw=4:ts=4:expandtab
"""
riko.modules
~~~~~~~~~~~~
"""

from riko import Context, Objconf, listize, objectify
from riko.bado.itertools import async_map
from riko.cast import CAST_SWITCH, BasicCastType, CastType, cast_none, cast_pass
from riko.cast import cast as cast_value
from riko.dotdict import DotDict, is_mapping
from riko.modules._assignment import _get_subpipe, gen_assignments, get_assignment
from riko.modules._decorators import Module, operator, processor, splitter
from riko.modules._inference import _gen_operator_return_kinds
from riko.modules._metadata import (
    _derive_loopable,
    _derive_subtypes,
    gen_module_catalog,
    list_modules,
)
from riko.modules._prepare import (
    PreparedModule,
    _dispatch,
    get_casters,
    get_parsers,
    get_pieces_or_conf,
)
from riko.parsers import conf_is_dynamic, get_field, get_skip, parse_conf
from riko.types.general import (
    AsyncOperatorParser,
    AsyncOperatorWrapper,
    AsyncProcessorParser,
    AsyncProcessorWrapper,
    AsyncSplitterParser,
    AsyncSplitterWrapper,
    Casted,
    CastFuncs,
    Conf,
    Defaults,
    Dispatched,
    Item,
    ItemOrValue,
    ModuleWrapper,
    OperatorParser,
    OperatorParserOutput,
    OperatorWrapper,
    OperatorWrapperInput,
    OperatorWrapperOutput,
    Opts,
    ParseFuncs,
    ParserOutput,
    Pipeline,
    PipeTuples,
    ProcessorParser,
    ProcessorParserOutput,
    ProcessorWrapper,
    ProcessorWrapperInput,
    ProcessorWrapperOutput,
    SplitterParser,
    SplitterWrapper,
    SplitterWrapperInput,
    Stream,
    StreamOrValueStream,
    Streams,
    SyncArgFunc,
    SyncConfCastFunc,
    SyncOperatorParser,
    SyncOperatorWrapper,
    SyncProcessorParser,
    SyncProcessorWrapper,
    SyncSplitterParser,
    SyncSplitterWrapper,
    ValueStream,
)
from riko.types.modules import (
    ConfValues,
    Embed,
    Inference,
    ModuleMetadata,
    ModuleSubtype,
    ModuleSubtypes,
    ModuleType,
    OperatorReturnKind,
)
from riko.types.values import (
    BasicReturn,
    NonstreamExpressions,
    PrimitiveValue,
    StatefulItem,
)
from riko.utils import broadcast, dispatch, parse_context

__all__ = [
    "CAST_SWITCH",
    "AsyncOperatorParser",
    "AsyncOperatorWrapper",
    "AsyncProcessorParser",
    "AsyncProcessorWrapper",
    "AsyncSplitterParser",
    "AsyncSplitterWrapper",
    "BasicCastType",
    "BasicReturn",
    "CastFuncs",
    "CastType",
    "Casted",
    "Conf",
    "ConfValues",
    "Context",
    "Defaults",
    "Dispatched",
    "DotDict",
    "Embed",
    "Inference",
    "Item",
    "ItemOrValue",
    "Module",
    "ModuleMetadata",
    "ModuleSubtype",
    "ModuleSubtypes",
    "ModuleType",
    "ModuleWrapper",
    "NonstreamExpressions",
    "Objconf",
    "OperatorParser",
    "OperatorParserOutput",
    "OperatorReturnKind",
    "OperatorWrapper",
    "OperatorWrapperInput",
    "OperatorWrapperOutput",
    "Opts",
    "ParseFuncs",
    "ParserOutput",
    "PipeTuples",
    "Pipeline",
    "PreparedModule",
    "PrimitiveValue",
    "ProcessorParser",
    "ProcessorParserOutput",
    "ProcessorWrapper",
    "ProcessorWrapperInput",
    "ProcessorWrapperOutput",
    "SplitterParser",
    "SplitterWrapper",
    "SplitterWrapperInput",
    "StatefulItem",
    "Stream",
    "StreamOrValueStream",
    "Streams",
    "SyncArgFunc",
    "SyncConfCastFunc",
    "SyncOperatorParser",
    "SyncOperatorWrapper",
    "SyncProcessorParser",
    "SyncProcessorWrapper",
    "SyncSplitterParser",
    "SyncSplitterWrapper",
    "ValueStream",
    "_derive_loopable",
    "_derive_subtypes",
    "_dispatch",
    "_gen_operator_return_kinds",
    "_get_subpipe",
    "async_map",
    "broadcast",
    "cast_none",
    "cast_pass",
    "cast_value",
    "conf_is_dynamic",
    "dispatch",
    "gen_assignments",
    "gen_module_catalog",
    "get_assignment",
    "get_casters",
    "get_field",
    "get_parsers",
    "get_pieces_or_conf",
    "get_skip",
    "is_mapping",
    "list_modules",
    "listize",
    "objectify",
    "operator",
    "parse_conf",
    "parse_context",
    "processor",
    "splitter",
]
