# Generated by riko codegen.
# Do not edit manually.

from riko.ext.names import ModuleName

__all__ = ["Modules", "Sinks", "Sources", "Transforms"]


class Sources(ModuleName):
    CSV = "csv"
    FEEDAUTODISCOVERY = "feedautodiscovery"
    FETCH = "fetch"
    FETCHDATA = "fetchdata"
    FETCHPAGE = "fetchpage"
    FETCHSITEFEED = "fetchsitefeed"
    FETCHTABLE = "fetchtable"
    FETCHTEXT = "fetchtext"
    FOREVER = "forever"
    INPUT = "input"
    ITEMBUILDER = "itembuilder"
    RSSITEMBUILDER = "rssitembuilder"
    URLBUILDER = "urlbuilder"
    XPATHFETCHPAGE = "xpathfetchpage"


class Transforms(ModuleName):
    AGGREGATE = "aggregate"
    COUNT = "count"
    CURRENCYFORMAT = "currencyformat"
    DATEBUILDER = "datebuilder"
    DATEFORMAT = "dateformat"
    EXCHANGERATE = "exchangerate"
    FILTER = "filter"
    GEOLOCATE = "geolocate"
    HASH = "hash"
    JOIN = "join"
    LOOP = "loop"
    RECEIVE = "receive"
    REFIND = "refind"
    REGEX = "regex"
    RENAME = "rename"
    REVERSE = "reverse"
    SEND = "send"
    SIMPLEMATH = "simplemath"
    SLUGIFY = "slugify"
    SORT = "sort"
    SPLIT = "split"
    STRCONCAT = "strconcat"
    STRFIND = "strfind"
    STRREPLACE = "strreplace"
    STRTRANSFORM = "strtransform"
    SUBELEMENT = "subelement"
    SUBSTR = "substr"
    SUM = "sum"
    TAIL = "tail"
    TIMEOUT = "timeout"
    TOKENIZER = "tokenizer"
    TRUNCATE = "truncate"
    TYPECAST = "typecast"
    UDF = "udf"
    UNION = "union"
    UNIQ = "uniq"
    URLPARSE = "urlparse"


class Sinks(ModuleName):
    WRITE = "write"


class Modules:
    AGGREGATE = Transforms.AGGREGATE
    COUNT = Transforms.COUNT
    CSV = Sources.CSV
    CURRENCYFORMAT = Transforms.CURRENCYFORMAT
    DATEBUILDER = Transforms.DATEBUILDER
    DATEFORMAT = Transforms.DATEFORMAT
    EXCHANGERATE = Transforms.EXCHANGERATE
    FEEDAUTODISCOVERY = Sources.FEEDAUTODISCOVERY
    FETCH = Sources.FETCH
    FETCHDATA = Sources.FETCHDATA
    FETCHPAGE = Sources.FETCHPAGE
    FETCHSITEFEED = Sources.FETCHSITEFEED
    FETCHTABLE = Sources.FETCHTABLE
    FETCHTEXT = Sources.FETCHTEXT
    FILTER = Transforms.FILTER
    FOREVER = Sources.FOREVER
    GEOLOCATE = Transforms.GEOLOCATE
    HASH = Transforms.HASH
    INPUT = Sources.INPUT
    ITEMBUILDER = Sources.ITEMBUILDER
    JOIN = Transforms.JOIN
    LOOP = Transforms.LOOP
    RECEIVE = Transforms.RECEIVE
    REFIND = Transforms.REFIND
    REGEX = Transforms.REGEX
    RENAME = Transforms.RENAME
    REVERSE = Transforms.REVERSE
    RSSITEMBUILDER = Sources.RSSITEMBUILDER
    SEND = Transforms.SEND
    SIMPLEMATH = Transforms.SIMPLEMATH
    SLUGIFY = Transforms.SLUGIFY
    SORT = Transforms.SORT
    SPLIT = Transforms.SPLIT
    STRCONCAT = Transforms.STRCONCAT
    STRFIND = Transforms.STRFIND
    STRREPLACE = Transforms.STRREPLACE
    STRTRANSFORM = Transforms.STRTRANSFORM
    SUBELEMENT = Transforms.SUBELEMENT
    SUBSTR = Transforms.SUBSTR
    SUM = Transforms.SUM
    TAIL = Transforms.TAIL
    TIMEOUT = Transforms.TIMEOUT
    TOKENIZER = Transforms.TOKENIZER
    TRUNCATE = Transforms.TRUNCATE
    TYPECAST = Transforms.TYPECAST
    UDF = Transforms.UDF
    UNION = Transforms.UNION
    UNIQ = Transforms.UNIQ
    URLBUILDER = Sources.URLBUILDER
    URLPARSE = Transforms.URLPARSE
    WRITE = Sinks.WRITE
    XPATHFETCHPAGE = Sources.XPATHFETCHPAGE
