# Pipe pipe_1a0ea1b39a8f261d0339a12fb5f0f03e generated by pipe2py

from riko import Context
from riko.modules.datebuilder import pipe as datebuilder
from riko.modules.dateformat import pipe as dateformat
from riko.modules.itembuilder import pipe as itembuilder


def pipe_1a0ea1b39a8f261d0339a12fb5f0f03e(item=None, conf=None, context=None, **kwargs):
    conf = conf or {}
    context = context or Context(**kwargs)

    if context.describe_input:
        return []

    if context.describe_dependencies:
        return ["pipedatebuilder", "pipedateformat", "itembuilder"]

    sw_385 = datebuilder(
        context=context, conf={"DATE": {"type": "datetime", "value": "12/2/2014"}}
    )

    sw_405 = dateformat(
        sw_385,
        conf={
            "timezone": {"type": "text", "value": ""},
            "format": {"type": "text", "value": "%B %d, %Y"},
        },
    )

    sw_393 = itembuilder(
        item,
        conf={
            "attrs": [
                {
                    "value": {"terminal": "attrs_1_value", "type": "text"},
                    "key": {"type": "text", "value": "date"},
                },
                {
                    "value": {"value": "1201", "type": "text"},
                    "key": {"type": "text", "value": "year"},
                },
            ]
        },
        attrs_1_value=sw_405,
        **kwargs,
    )

    return sw_393


if __name__ == "__main__":
    for i in pipe_1a0ea1b39a8f261d0339a12fb5f0f03e(context=Context()):
        print(i)
