# -*- coding: utf-8 -*-
# vim: sw=4:ts=4:expandtab
# Pipe pipe_679e2c544332e978b15b6b163767975f generated by pipe2py

from riko import Context
from riko.modules.itembuilder import pipe as itembuilder
from riko.modules.strreplace import pipe as strreplace


def pipe_679e2c544332e978b15b6b163767975f(item=None, conf=None, context=None, **kwargs):
    conf = conf or {}
    context = context or Context(**kwargs)

    if context.describe_input:
        return []

    if context.describe_dependencies:
        return ["itembuilder", "strreplace"]

    sw_232 = itembuilder(
        item,
        conf={
            "attrs": [
                {
                    "value": {"type": "text", "value": "www.google.com"},
                    "key": {"type": "text", "value": "link"},
                },
                {
                    "value": {"type": "text", "value": "google"},
                    "key": {"type": "text", "value": "title"},
                },
                {
                    "value": {"type": "text", "value": "$"},
                    "key": {"type": "text", "value": "author"},
                },
            ]
        },
        **kwargs
    )

    sw_421_conf = {
        "field": {"type": "text", "value": "author"},
        "rule": [
            {
                "find": {"type": "text", "value": "$"},
                "param": {"type": "text", "value": "first"},
                "replace": {"type": "text", "value": "USD"},
            }
        ],
    }

    output = (strreplace(i, conf=sw_421_conf, **kwargs) for i in sw_232)
    return output


if __name__ == "__main__":
    for i in pipe_679e2c544332e978b15b6b163767975f():
        print(i)
