# vim: sw=4:ts=4:expandtab
"""
riko.currencies
~~~~~~~~~~~~~~~

Provides currency lookup dictionaries.

Symbols resolve to ISO 4217 codes, and each code resolves to a record of the
currency's names, symbols, and locale. Only ``code`` and ``location`` are
guaranteed; a handful of withdrawn currencies omit ``locale`` or the name and
symbol fields, so read the optional ones with ``get``.

Examples:
    Basic usage::

        >>> from riko.currencies import CURRENCY_CODES, CURRENCY_SYMBOLS
        >>>
        >>> CURRENCY_SYMBOLS["$"]
        'USD'
        >>> CURRENCY_CODES["USD"]["name"]
        'US Dollar'
        >>> CURRENCY_CODES["ZWL"].get("name", "unnamed")
        'unnamed'

Attributes:
    CURRENCY_SYMBOLS: Currency symbol to ISO 4217 code mapping.
    CURRENCY_CODES: ISO 4217 code to currency record mapping.

"""

from riko.types._locations import CurrencyCode

CURRENCY_SYMBOLS = {
    "$": "USD",
    "£": "GBP",
    "€": "EUR",
    "₹": "INR",
}

CURRENCY_CODES: dict[str, CurrencyCode] = {
    "AED": {
        "code": "AED",
        "location": "United Arab Emirates",
        "name": "United Arab Emirates Dirham",
        "name_plural": "UAE dirhams",
        "symbol": "AED",
        "symbol_native": "د.إ.",
        "locale": "ar_AE",
    },
    "AFN": {
        "code": "AFN",
        "location": "Afghanistan",
        "name": "Afghan Afghani",
        "name_plural": "Afghan Afghanis",
        "symbol": "Af",
        "symbol_native": "؋",
        "locale": "ps_AF",
    },
    "ALL": {
        "code": "ALL",
        "location": "Albania",
        "name": "Albanian Lek",
        "name_plural": "Albanian lekë",
        "symbol": "ALL",
        "symbol_native": "Lek",
        "locale": "sq_AL",
    },
    "AMD": {
        "code": "AMD",
        "location": "Armenia",
        "name": "Armenian Dram",
        "name_plural": "Armenian drams",
        "symbol": "AMD",
        "symbol_native": "դր.",
        "locale": "hy_AM",
    },
    "ARS": {
        "code": "ARS",
        "location": "Argentina",
        "name": "Argentine Peso",
        "name_plural": "Argentine pesos",
        "symbol": "AR$",
        "symbol_native": "$",
        "locale": "es_AR",
    },
    "AUD": {
        "code": "AUD",
        "location": "Australia",
        "name": "Australian Dollar",
        "name_plural": "Australian dollars",
        "symbol": "AU$",
        "symbol_native": "$",
        "locale": "en_AU",
    },
    "AZN": {
        "code": "AZN",
        "location": "Azerbaijan",
        "name": "Azerbaijani Manat",
        "name_plural": "Azerbaijani manats",
        "symbol": "man.",
        "symbol_native": "ман.",
        "locale": "az_AZ",
    },
    "BAM": {
        "code": "BAM",
        "location": "Bosnia and Herzegovina",
        "name": "Bosnia-Herzegovina Convertible Mark",
        "name_plural": "Bosnia-Herzegovina convertible marks",
        "symbol": "KM",
        "symbol_native": "KM",
        "locale": "bs_BA",
    },
    "BDT": {
        "code": "BDT",
        "location": "Bangladesh",
        "name": "Bangladeshi Taka",
        "name_plural": "Bangladeshi takas",
        "symbol": "Tk",
        "symbol_native": "৳",
        "locale": "bn_BD",
    },
    "BGN": {
        "code": "BGN",
        "location": "Bulgaria",
        "name": "Bulgarian Lev",
        "name_plural": "Bulgarian leva",
        "symbol": "BGN",
        "symbol_native": "лв.",
        "locale": "bg_BG",
    },
    "BHD": {
        "code": "BHD",
        "location": "Bahrain",
        "name": "Bahraini Dinar",
        "name_plural": "Bahraini dinars",
        "symbol": "BD",
        "symbol_native": "د.ب.",
        "locale": "ar_BH",
    },
    "BIF": {
        "code": "BIF",
        "location": "Burundi",
        "name": "Burundian Franc",
        "name_plural": "Burundian francs",
        "symbol": "FBu",
        "symbol_native": "FBu",
        "locale": "fr_BI",
    },
    "BND": {
        "code": "BND",
        "location": "Brunei",
        "name": "Brunei Dollar",
        "name_plural": "Brunei dollars",
        "symbol": "BN$",
        "symbol_native": "$",
        "locale": "ms_BN",
    },
    "BOB": {
        "code": "BOB",
        "location": "Bolivia",
        "name": "Bolivian Boliviano",
        "name_plural": "Bolivian bolivianos",
        "symbol": "Bs",
        "symbol_native": "Bs",
        "locale": "es_BO",
    },
    "BRL": {
        "code": "BRL",
        "location": "Brazil",
        "name": "Brazilian Real",
        "name_plural": "Brazilian reals",
        "symbol": "R$",
        "symbol_native": "R$",
        "locale": "pt_BR",
    },
    "BWP": {
        "code": "BWP",
        "location": "Botswana",
        "name": "Botswanan Pula",
        "name_plural": "Botswanan pulas",
        "symbol": "BWP",
        "symbol_native": "P",
        "locale": "en_BW",
    },
    "BYR": {
        "code": "BYR",
        "location": "Belarus",
        "name": "Belarusian Ruble",
        "name_plural": "Belarusian rubles",
        "symbol": "BYR",
        "symbol_native": "BYR",
        "locale": "be_BY",
    },
    "BZD": {
        "code": "BZD",
        "location": "Belize",
        "name": "Belize Dollar",
        "name_plural": "Belize dollars",
        "symbol": "BZ$",
        "symbol_native": "$",
        "locale": "en_BZ",
    },
    "CAD": {
        "code": "CAD",
        "location": "Canada",
        "name": "Canadian Dollar",
        "name_plural": "Canadian dollars",
        "symbol": "CA$",
        "symbol_native": "$",
        "locale": "en_CA",
    },
    "CDF": {
        "code": "CDF",
        "location": "Democratic Republic of the Congo",
        "name": "Congolese Franc",
        "name_plural": "Congolese francs",
        "symbol": "CDF",
        "symbol_native": "FrCD",
        "locale": "fr_CD",
    },
    "CHF": {
        "code": "CHF",
        "location": "Switzerland",
        "name": "Swiss Franc",
        "name_plural": "Swiss francs",
        "symbol": "CHF",
        "symbol_native": "CHF",
        "locale": "de_CH",
    },
    "CLP": {
        "code": "CLP",
        "location": "Chile",
        "name": "Chilean Peso",
        "name_plural": "Chilean pesos",
        "symbol": "CL$",
        "symbol_native": "$",
        "locale": "es_CL",
    },
    "CNY": {
        "code": "CNY",
        "location": "China",
        "name": "Chinese Yuan",
        "name_plural": "Chinese yuan",
        "symbol": "CN¥",
        "symbol_native": "CN¥",
        "locale": "zh_CN",
    },
    "COP": {
        "code": "COP",
        "location": "Colombia",
        "name": "Colombian Peso",
        "name_plural": "Colombian pesos",
        "symbol": "CO$",
        "symbol_native": "$",
        "locale": "es_CO",
    },
    "CRC": {
        "code": "CRC",
        "location": "Costa Rica",
        "name": "Costa Rican Colón",
        "name_plural": "Costa Rican colóns",
        "symbol": "₡",
        "symbol_native": "₡",
        "locale": "es_CR",
    },
    "CVE": {
        "code": "CVE",
        "location": "Cape Verde",
        "name": "Cape Verdean Escudo",
        "name_plural": "Cape Verdean escudos",
        "symbol": "CV$",
        "symbol_native": "CV$",
        "locale": "pt_CV",
    },
    "CZK": {
        "code": "CZK",
        "location": "Czech Republic",
        "name": "Czech Republic Koruna",
        "name_plural": "Czech Republic korunas",
        "symbol": "Kč",
        "symbol_native": "Kč",
        "locale": "cs_CZ",
    },
    "DJF": {
        "code": "DJF",
        "location": "Djibouti",
        "name": "Djiboutian Franc",
        "name_plural": "Djiboutian francs",
        "symbol": "Fdj",
        "symbol_native": "Fdj",
        "locale": "fr_DJ",
    },
    "DKK": {
        "code": "DKK",
        "location": "Denmark",
        "name": "Danish Krone",
        "name_plural": "Danish kroner",
        "symbol": "Dkr",
        "symbol_native": "kr",
        "locale": "da_DK",
    },
    "DOP": {
        "code": "DOP",
        "location": "Dominican Republic",
        "name": "Dominican Peso",
        "name_plural": "Dominican pesos",
        "symbol": "RD$",
        "symbol_native": "RD$",
        "locale": "es_DO",
    },
    "DZD": {
        "code": "DZD",
        "location": "Algeria",
        "name": "Algerian Dinar",
        "name_plural": "Algerian dinars",
        "symbol": "DA",
        "symbol_native": "د.ج.",
        "locale": "ar_DZ",
    },
    "EEK": {
        "code": "EEK",
        "location": "Estonia",
        "name": "Estonian Kroon",
        "name_plural": "Estonian kroons",
        "symbol": "Ekr",
        "symbol_native": "kr",
    },
    "EGP": {
        "code": "EGP",
        "location": "Egypt",
        "name": "Egyptian Pound",
        "name_plural": "Egyptian pounds",
        "symbol": "EGP",
        "symbol_native": "ج.م.",
        "locale": "ar_EG",
    },
    "ERN": {
        "code": "ERN",
        "location": "Eritrea",
        "name": "Eritrean Nakfa",
        "name_plural": "Eritrean nakfas",
        "symbol": "Nfk",
        "symbol_native": "Nfk",
        "locale": "en_ER",
    },
    "ETB": {
        "code": "ETB",
        "location": "Ethiopia",
        "name": "Ethiopian Birr",
        "name_plural": "Ethiopian birrs",
        "symbol": "Br",
        "symbol_native": "Br",
        "locale": "am_ET",
    },
    "EUR": {
        "code": "EUR",
        "location": "European Union",
        "name": "Euro",
        "name_plural": "euros",
        "symbol": "€",
        "symbol_native": "€",
        "locale": "de_BE",
    },
    "GBP": {
        "code": "GBP",
        "location": "United Kingdom",
        "name": "British Pound Sterling",
        "name_plural": "British pounds sterling",
        "symbol": "£",
        "symbol_native": "£",
        "locale": "en_GB",
    },
    "GEL": {
        "code": "GEL",
        "location": "Georgia",
        "name": "Georgian Lari",
        "name_plural": "Georgian laris",
        "symbol": "GEL",
        "symbol_native": "GEL",
        "locale": "ka_GE",
    },
    "GHS": {
        "code": "GHS",
        "location": "Ghana",
        "name": "Ghanaian Cedi",
        "name_plural": "Ghanaian cedis",
        "symbol": "GH₵",
        "symbol_native": "GH₵",
        "locale": "en_GH",
    },
    "GNF": {
        "code": "GNF",
        "location": "Guinea",
        "name": "Guinean Franc",
        "name_plural": "Guinean francs",
        "symbol": "FG",
        "symbol_native": "FG",
        "locale": "fr_GN",
    },
    "GTQ": {
        "code": "GTQ",
        "location": "Guatemala",
        "name": "Guatemalan Quetzal",
        "name_plural": "Guatemalan quetzals",
        "symbol": "GTQ",
        "symbol_native": "Q",
        "locale": "es_GT",
    },
    "HKD": {
        "code": "HKD",
        "location": "Hong Kong",
        "name": "Hong Kong Dollar",
        "name_plural": "Hong Kong dollars",
        "symbol": "HK$",
        "symbol_native": "$",
        "locale": "en_HK",
    },
    "HNL": {
        "code": "HNL",
        "location": "Honduras",
        "name": "Honduran Lempira",
        "name_plural": "Honduran lempiras",
        "symbol": "HNL",
        "symbol_native": "L",
        "locale": "es_HN",
    },
    "HRK": {
        "code": "HRK",
        "location": "Croatia",
        "name": "Croatian Kuna",
        "name_plural": "Croatian kunas",
        "symbol": "kn",
        "symbol_native": "kn",
    },
    "HUF": {
        "code": "HUF",
        "location": "Hungary",
        "name": "Hungarian Forint",
        "name_plural": "Hungarian forints",
        "symbol": "Ft",
        "symbol_native": "Ft",
        "locale": "hu_HU",
    },
    "IDR": {
        "code": "IDR",
        "location": "Indonesia",
        "name": "Indonesian Rupiah",
        "name_plural": "Indonesian rupiahs",
        "symbol": "Rp",
        "symbol_native": "Rp",
        "locale": "id_ID",
    },
    "ILS": {
        "code": "ILS",
        "location": "Israel",
        "name": "Israeli New Sheqel",
        "name_plural": "Israeli new sheqels",
        "symbol": "₪",
        "symbol_native": "₪",
        "locale": "he_IL",
    },
    "INR": {
        "code": "INR",
        "location": "India",
        "name": "Indian Rupee",
        "name_plural": "Indian rupees",
        "symbol": "Rs",
        "symbol_native": "₹",
        "locale": "en_IN",
    },
    "IQD": {
        "code": "IQD",
        "location": "Iraq",
        "name": "Iraqi Dinar",
        "name_plural": "Iraqi dinars",
        "symbol": "IQD",
        "symbol_native": "د.ع.",
        "locale": "ar_IQ",
    },
    "IRR": {
        "code": "IRR",
        "location": "Iran",
        "name": "Iranian Rial",
        "name_plural": "Iranian rials",
        "symbol": "IRR",
        "symbol_native": "﷼",
        "locale": "fa_IR",
    },
    "ISK": {
        "code": "ISK",
        "location": "Iceland",
        "name": "Icelandic Króna",
        "name_plural": "Icelandic krónur",
        "symbol": "Ikr",
        "symbol_native": "kr",
        "locale": "is_IS",
    },
    "JMD": {
        "code": "JMD",
        "location": "Jamaica",
        "name": "Jamaican Dollar",
        "name_plural": "Jamaican dollars",
        "symbol": "J$",
        "symbol_native": "$",
        "locale": "en_JM",
    },
    "JOD": {
        "code": "JOD",
        "location": "Jordan",
        "name": "Jordanian Dinar",
        "name_plural": "Jordanian dinars",
        "symbol": "JD",
        "symbol_native": "د.أ.",
        "locale": "ar_JO",
    },
    "JPY": {
        "code": "JPY",
        "location": "Japan",
        "name": "Japanese Yen",
        "name_plural": "Japanese yen",
        "symbol": "¥",
        "symbol_native": "￥",
        "locale": "ja_JP",
    },
    "KES": {
        "code": "KES",
        "location": "Kenya",
        "name": "Kenyan Shilling",
        "name_plural": "Kenyan shillings",
        "symbol": "Ksh",
        "symbol_native": "/–",
        "locale": "en_KE",
    },
    "KHR": {
        "code": "KHR",
        "location": "Cambodia",
        "name": "Cambodian Riel",
        "name_plural": "Cambodian riels",
        "symbol": "KHR",
        "symbol_native": "៛",
        "locale": "km_KH",
    },
    "KMF": {
        "code": "KMF",
        "location": "Comoros",
        "name": "Comorian Franc",
        "name_plural": "Comorian francs",
        "symbol": "CF",
        "symbol_native": "FC",
        "locale": "fr_KM",
    },
    "KRW": {
        "code": "KRW",
        "location": "South Korea",
        "name": "South Korean Won",
        "name_plural": "South Korean won",
        "symbol": "₩",
        "symbol_native": "₩",
        "locale": "ko_KR",
    },
    "KWD": {
        "code": "KWD",
        "location": "Kuwait",
        "name": "Kuwaiti Dinar",
        "name_plural": "Kuwaiti dinars",
        "symbol": "KD",
        "symbol_native": "د.ك.",
        "locale": "ar_KW",
    },
    "KZT": {
        "code": "KZT",
        "location": "Kazakhstan",
        "name": "Kazakhstani Tenge",
        "name_plural": "Kazakhstani tenges",
        "symbol": "KZT",
        "symbol_native": "тңг.",
        "locale": "kk_KZ",
    },
    "LBP": {
        "code": "LBP",
        "location": "Lebanon",
        "name": "Lebanese Pound",
        "name_plural": "Lebanese pounds",
        "symbol": "LB£",
        "symbol_native": "ل.ل.",
        "locale": "fr_LB",
    },
    "LKR": {
        "code": "LKR",
        "location": "Sri Lanka",
        "name": "Sri Lankan Rupee",
        "name_plural": "Sri Lankan rupees",
        "symbol": "SLRs",
        "symbol_native": "SL Re",
        "locale": "si_LK",
    },
    "LTL": {
        "code": "LTL",
        "location": "Lithuania",
        "name": "Lithuanian Litas",
        "name_plural": "Lithuanian litai",
        "symbol": "Lt",
        "symbol_native": "Lt",
    },
    "LVL": {
        "code": "LVL",
        "location": "Latvia",
        "name": "Latvian Lats",
        "name_plural": "Latvian lati",
        "symbol": "Ls",
        "symbol_native": "Ls",
    },
    "LYD": {
        "code": "LYD",
        "location": "Libya",
        "name": "Libyan Dinar",
        "name_plural": "Libyan dinars",
        "symbol": "LD",
        "symbol_native": "د.ل.",
        "locale": "ar_LY",
    },
    "MAD": {
        "code": "MAD",
        "location": "Morocco",
        "name": "Moroccan Dirham",
        "name_plural": "Moroccan dirhams",
        "symbol": "MAD",
        "symbol_native": "د.م.",
        "locale": "es_EH",
    },
    "MDL": {
        "code": "MDL",
        "location": "Moldova",
        "name": "Moldovan Leu",
        "name_plural": "Moldovan lei",
        "symbol": "MDL",
        "symbol_native": "MDL",
        "locale": "ro_MD",
    },
    "MGA": {
        "code": "MGA",
        "location": "Madagascar",
        "name": "Malagasy Ariary",
        "name_plural": "Malagasy Ariaries",
        "symbol": "MGA",
        "symbol_native": "MGA",
        "locale": "mg_MG",
    },
    "MKD": {
        "code": "MKD",
        "location": "Macedonia",
        "name": "Macedonian Denar",
        "name_plural": "Macedonian denari",
        "symbol": "MKD",
        "symbol_native": "MKD",
        "locale": "mk_MK",
    },
    "MMK": {
        "code": "MMK",
        "location": "Myanmar",
        "name": "Myanma Kyat",
        "name_plural": "Myanma kyats",
        "symbol": "MMK",
        "symbol_native": "K",
        "locale": "my_MM",
    },
    "MOP": {
        "code": "MOP",
        "location": "Macao",
        "name": "Macanese Pataca",
        "name_plural": "Macanese patacas",
        "symbol": "MOP$",
        "symbol_native": "MOP$",
        "locale": "pt_MO",
    },
    "MUR": {
        "code": "MUR",
        "location": "Mauritius",
        "name": "Mauritian Rupee",
        "name_plural": "Mauritian rupees",
        "symbol": "MURs",
        "symbol_native": "MURs",
        "locale": "en_MU",
    },
    "MXN": {
        "code": "MXN",
        "location": "Mexico",
        "name": "Mexican Peso",
        "name_plural": "Mexican pesos",
        "symbol": "MX$",
        "symbol_native": "$",
        "locale": "es_MX",
    },
    "MYR": {
        "code": "MYR",
        "location": "Malaysia",
        "name": "Malaysian Ringgit",
        "name_plural": "Malaysian ringgits",
        "symbol": "RM",
        "symbol_native": "RM",
        "locale": "ms_MY",
    },
    "MZN": {
        "code": "MZN",
        "location": "Mozambique",
        "name": "Mozambican Metical",
        "name_plural": "Mozambican meticals",
        "symbol": "MTn",
        "symbol_native": "MTn",
        "locale": "pt_MZ",
    },
    "NAD": {
        "code": "NAD",
        "location": "Namibia",
        "name": "Namibian Dollar",
        "name_plural": "Namibian dollars",
        "symbol": "N$",
        "symbol_native": "N$",
        "locale": "en_NA",
    },
    "NGN": {
        "code": "NGN",
        "location": "Nigeria",
        "name": "Nigerian Naira",
        "name_plural": "Nigerian nairas",
        "symbol": "₦",
        "symbol_native": "₦",
        "locale": "en_NG",
    },
    "NIO": {
        "code": "NIO",
        "location": "Nicaragua",
        "name": "Nicaraguan Córdoba",
        "name_plural": "Nicaraguan córdobas",
        "symbol": "C$",
        "symbol_native": "C$",
        "locale": "es_NI",
    },
    "NOK": {
        "code": "NOK",
        "location": "Norway",
        "name": "Norwegian Krone",
        "name_plural": "Norwegian kroner",
        "symbol": "Nkr",
        "symbol_native": "kr",
        "locale": "no_NO",
    },
    "NPR": {
        "code": "NPR",
        "location": "Nepal",
        "name": "Nepalese Rupee",
        "name_plural": "Nepalese rupees",
        "symbol": "NPRs",
        "symbol_native": "नेरू",
        "locale": "ne_NP",
    },
    "NZD": {
        "code": "NZD",
        "location": "New Zealand",
        "name": "New Zealand Dollar",
        "name_plural": "New Zealand dollars",
        "symbol": "NZ$",
        "symbol_native": "$",
        "locale": "en_NZ",
    },
    "OMR": {
        "code": "OMR",
        "location": "Oman",
        "name": "Omani Rial",
        "name_plural": "Omani rials",
        "symbol": "OMR",
        "symbol_native": "ر.ع.",
        "locale": "ar_OM",
    },
    "PAB": {
        "code": "PAB",
        "location": "Panama",
        "name": "Panamanian Balboa",
        "name_plural": "Panamanian balboas",
        "symbol": "B/.",
        "symbol_native": "B/.",
        "locale": "es_PA",
    },
    "PEN": {
        "code": "PEN",
        "location": "Peru",
        "name": "Peruvian Nuevo Sol",
        "name_plural": "Peruvian nuevos soles",
        "symbol": "S/.",
        "symbol_native": "S/.",
        "locale": "es_PE",
    },
    "PHP": {
        "code": "PHP",
        "location": "Philippines",
        "name": "Philippine Peso",
        "name_plural": "Philippine pesos",
        "symbol": "₱",
        "symbol_native": "₱",
        "locale": "en_PH",
    },
    "PKR": {
        "code": "PKR",
        "location": "Pakistan",
        "name": "Pakistani Rupee",
        "name_plural": "Pakistani rupees",
        "symbol": "PKRs",
        "symbol_native": "₨",
        "locale": "en_PK",
    },
    "PLN": {
        "code": "PLN",
        "location": "Poland",
        "name": "Polish Zloty",
        "name_plural": "Polish zlotys",
        "symbol": "zł",
        "symbol_native": "zł",
        "locale": "pl_PL",
    },
    "PYG": {
        "code": "PYG",
        "location": "Paraguay",
        "name": "Paraguayan Guarani",
        "name_plural": "Paraguayan guaranis",
        "symbol": "₲",
        "symbol_native": "₲",
        "locale": "es_PY",
    },
    "QAR": {
        "code": "QAR",
        "location": "Qatar",
        "name": "Qatari Rial",
        "name_plural": "Qatari rials",
        "symbol": "QR",
        "symbol_native": "ر.ق.",
        "locale": "ar_QA",
    },
    "RON": {
        "code": "RON",
        "location": "Romania",
        "name": "Romanian Leu",
        "name_plural": "Romanian lei",
        "symbol": "RON",
        "symbol_native": "RON",
        "locale": "ro_RO",
    },
    "RSD": {
        "code": "RSD",
        "location": "Serbia",
        "name": "Serbian Dinar",
        "name_plural": "Serbian dinars",
        "symbol": "din.",
        "symbol_native": "дин.",
        "locale": "sr_RS",
    },
    "RUB": {
        "code": "RUB",
        "location": "Russia",
        "name": "Russian Ruble",
        "name_plural": "Russian rubles",
        "symbol": "RUB",
        "symbol_native": "руб.",
        "locale": "ru_RU",
    },
    "RWF": {
        "code": "RWF",
        "location": "Rwanda",
        "name": "Rwandan Franc",
        "name_plural": "Rwandan francs",
        "symbol": "RWF",
        "symbol_native": "FR",
        "locale": "en_RW",
    },
    "SAR": {
        "code": "SAR",
        "location": "Saudi Arabia",
        "name": "Saudi Riyal",
        "name_plural": "Saudi riyals",
        "symbol": "SR",
        "symbol_native": "ر.س.",
        "locale": "ar_SA",
    },
    "SDG": {
        "code": "SDG",
        "location": "Sudan",
        "name": "Sudanese Pound",
        "name_plural": "Sudanese pounds",
        "symbol": "SDG",
        "symbol_native": "SDG",
        "locale": "en_SD",
    },
    "SEK": {
        "code": "SEK",
        "location": "Sweden",
        "name": "Swedish Krona",
        "name_plural": "Swedish kronor",
        "symbol": "Skr",
        "symbol_native": "kr",
        "locale": "sv_SE",
    },
    "SGD": {
        "code": "SGD",
        "location": "Singapore",
        "name": "Singapore Dollar",
        "name_plural": "Singapore dollars",
        "symbol": "S$",
        "symbol_native": "$",
        "locale": "en_SG",
    },
    "SOS": {
        "code": "SOS",
        "location": "Somalia",
        "name": "Somali Shilling",
        "name_plural": "Somali shillings",
        "symbol": "Ssh",
        "symbol_native": "Ssh",
        "locale": "so_SO",
    },
    "SYP": {
        "code": "SYP",
        "location": "Syria",
        "name": "Syrian Pound",
        "name_plural": "Syrian pounds",
        "symbol": "SY£",
        "symbol_native": "ل.س.",
        "locale": "ar_SY",
    },
    "THB": {
        "code": "THB",
        "location": "Thailand",
        "name": "Thai Baht",
        "name_plural": "Thai baht",
        "symbol": "฿",
        "symbol_native": "฿",
        "locale": "th_TH",
    },
    "TND": {
        "code": "TND",
        "location": "Tunisia",
        "name": "Tunisian Dinar",
        "name_plural": "Tunisian dinars",
        "symbol": "DT",
        "symbol_native": "د.ت.",
        "locale": "ar_TN",
    },
    "TOP": {
        "code": "TOP",
        "location": "Tonga",
        "name": "Tongan Paʻanga",
        "name_plural": "Tongan paʻanga",
        "symbol": "T$",
        "symbol_native": "T$",
        "locale": "en_TO",
    },
    "TRY": {
        "code": "TRY",
        "location": "Turkey",
        "name": "Turkish Lira",
        "name_plural": "Turkish Lira",
        "symbol": "TL",
        "symbol_native": "₤",
        "locale": "tr_TR",
    },
    "TTD": {
        "code": "TTD",
        "location": "Trinidad and Tobago",
        "name": "Trinidad and Tobago Dollar",
        "name_plural": "Trinidad and Tobago dollars",
        "symbol": "TT$",
        "symbol_native": "$",
        "locale": "en_TT",
    },
    "TWD": {
        "code": "TWD",
        "location": "Taiwan",
        "name": "New Taiwan Dollar",
        "name_plural": "New Taiwan dollars",
        "symbol": "NT$",
        "symbol_native": "NT$",
        "locale": "zh_TW",
    },
    "TZS": {
        "code": "TZS",
        "location": "Tanzania",
        "name": "Tanzanian Shilling",
        "name_plural": "Tanzanian shillings",
        "symbol": "TSh",
        "symbol_native": "/–",
        "locale": "en_TZ",
    },
    "UAH": {
        "code": "UAH",
        "location": "Ukraine",
        "name": "Ukrainian Hryvnia",
        "name_plural": "Ukrainian hryvnias",
        "symbol": "₴",
        "symbol_native": "₴",
        "locale": "uk_UA",
    },
    "UGX": {
        "code": "UGX",
        "location": "Uganda",
        "name": "Ugandan Shilling",
        "name_plural": "Ugandan shillings",
        "symbol": "USh",
        "symbol_native": "USh",
        "locale": "en_UG",
    },
    "USD": {
        "code": "USD",
        "location": "United States",
        "name": "US Dollar",
        "name_plural": "US dollars",
        "symbol": "$",
        "symbol_native": "$",
        "locale": "en_US",
    },
    "UYU": {
        "code": "UYU",
        "location": "Uruguay",
        "name": "Uruguayan Peso",
        "name_plural": "Uruguayan pesos",
        "symbol": "$U",
        "symbol_native": "$",
        "locale": "es_UY",
    },
    "UZS": {
        "code": "UZS",
        "location": "Uzbekistan",
        "name": "Uzbekistan Som",
        "name_plural": "Uzbekistan som",
        "symbol": "UZS",
        "symbol_native": "UZS",
        "locale": "uz_UZ",
    },
    "VEF": {
        "code": "VEF",
        "location": "Venezuela",
        "name": "Venezuelan Bolívar",
        "name_plural": "Venezuelan bolívars",
        "symbol": "Bs.F.",
        "symbol_native": "Bs.F.",
    },
    "VND": {
        "code": "VND",
        "location": "Vietnam",
        "name": "Vietnamese Dong",
        "name_plural": "Vietnamese dong",
        "symbol": "₫",
        "symbol_native": "₫",
        "locale": "vi_VN",
    },
    "XAF": {
        "code": "XAF",
        "location": "Cameroon",
        "name": "CFA Franc BEAC",
        "name_plural": "CFA francs BEAC",
        "symbol": "FCFA",
        "symbol_native": "FCFA",
        "locale": "en_CM",
    },
    "XOF": {
        "code": "XOF",
        "location": "Benin",
        "name": "CFA Franc BCEAO",
        "name_plural": "CFA francs BCEAO",
        "symbol": "CFA",
        "symbol_native": "CFA",
        "locale": "fr_BJ",
    },
    "YER": {
        "code": "YER",
        "location": "Yemen",
        "name": "Yemeni Rial",
        "name_plural": "Yemeni rials",
        "symbol": "YR",
        "symbol_native": "ر.ي.",
        "locale": "ar_YE",
    },
    "ZAR": {
        "code": "ZAR",
        "location": "South Africa",
        "name": "South African Rand",
        "name_plural": "South African rand",
        "symbol": "R",
        "symbol_native": "R",
        "locale": "en_ZA",
    },
    "ZMK": {
        "code": "ZMK",
        "name": "Zambian Kwacha",
        "location": "Zambia",
        "name_plural": "Zambian kwachas",
        "symbol": "ZK",
        "symbol_native": "ZK",
    },
    "ZWL": {
        "code": "ZWL",
        "location": "Zimbabwe",
        "locale": "en_ZW",
    },
}
